### ISSUE TITLE
`Indexed` breaks type checkers

### ISSUE THREAD

**Issue by tonybaloney** [roman-right/beanie#105]
The `Indexed` type annotation is raising a warning from Pylance (and other type checkers), because the the result of `Indexed()` is not annotated as any particular type.

```python
class Address(Document):
    street_number: int
    street_name: str
    city: str
    country: str
    longitude: str
    latitude: str
    postal_code: Indexed(str)  # We sort on postal codes, so index them

    class Collection:
        name = "addresses"
```

I _think_, looking at the code, its a `Union[T, _Indexed]` where:

```python
class _Indexed:
    _indexed : Tuple[Any,Dict]

T = TypeVar("T")

def Indexed(typ: T, index_type=ASCENDING, **kwargs) -> Union[T, _Indexed]: 
    ...
```

**Comment by tonybaloney** [comment]
The Pylance error is Illegal type annotation: call expression not allowedPylance

**Comment by tonybaloney** [comment]
@roman-right I have an idea how this could be done, I'll submit a PR if you want

**Comment by gegnew** [comment]
Any thoughts about when this might be fixed?
