### ISSUE TITLE
Case insensitive sorting on multiple field

### ISSUE THREAD

**Issue by terravi** [roman-right/beanie#111]
I need to be able to sort documents by multiple fields in case insensitive mode. In mongo db I could do this with collations and strength at 1. I have not found a way to use collations with beanie.

**Comment by terravi** [comment]
I have solved deriving FindMany in my project and overriding the motor_cursor property in order to pass the collation parameter to the find method of the AsyncIOMotorCollection motor class

class CustomFindMany(FindMany):
    def __init__(self, instance: FindMany):
        self.parent = instance
        self.collation_expressions = None

    def collation(self, collation):
        if collation is not None:
            self.collation_expressions = collation
        return self

    def __getattr__(self, name):
        return getattr(self.parent, name)

    @property
    def motor_cursor(self):
        return self.document_model.get_motor_collection().find(
            filter=self.get_filter_query(),
            sort=self.sort_expressions,
            projection=get_projection(self.projection_model),
            skip=self.skip_number,
            limit=self.limit_number,
            collation=self.collation_expressions,
            session=self.session,
        )

**Comment by roman-right** [comment]
Hey @terravi ,

Thank you for the input. It looks like an important feature. I'll add this to Beanie soon.

**Comment by hosamk92** [comment]
I faced this earlier couldn't find docs on how to achieve it, but it can be achieved now just by adding the collation param to the find function: 

```
model_type.find(
            query,
            collation={"locale": "en", "strength": 2}  # handle case-insensitive sorts
        ).sort((field, sort_order)).to_list()
```
