### ISSUE TITLE
projections does not show _id

### ISSUE THREAD

**Issue by Cristianasp** [roman-right/beanie#117]
Hello Roman !

I am using projections to limit the amount of data of a collection, but when I use it, the field _id does not projects.
Is this a normal behavior ?

```
from beanie import PydanticObjectId

class EpicShortView(BaseModel):
    _id: PydanticObjectId 
    external_id: str = None
    business: str = None

class Epic(Document):
    class Collection:
        name = 'epics'
    external_id: str = None
    business: str = None
    epic_name: str = None
    epic_owner: str = None
    epic_idea: str = None
    epic_description: str  = None
```

`Epic.find(Epic.business == business).project(EpicShortView).to_list()` does not return `_id`

Thank you

**Comment by roman-right** [comment]
Hi @Cristianasp ,

Yup, this is pydantic-specific thing. It thinks that _id is class property, not object field (bc it starts with '_'). To solve this you can use an alias.

```python
class EpicShortView(BaseModel):
    id: PydanticObjectId = Field(alias='_id')
    external_id: str = None
    business: str = None
```

Thank you for the question :)
Pls, let me know if it helped.

**Comment by Cristianasp** [comment]
Hello Roman, yes, it worked :-) Thank you

**Comment by snjypl** [comment]
i think, it would be good if we add this as part of the projection documentation.
