### ISSUE TITLE
Fields not showing in pycharm

### ISSUE THREAD

**Issue by zrothberg** [roman-right/beanie#120]
So it works great. Seriously love this lib. Is there anyway to get the fields to be visible when typing in pycharm? Does it work in any other ides? Everything looks fine when I pop it under the debugger.

**Comment by roman-right** [comment]
Hey! Thank you :)

Could you please give me an example of this behavior? This is a very important part for me - to make a tool, which will be comfortable to use.

Here is how my pycharm offers field names:

![screenshot](https://i.ibb.co/NFGhj81/Screenshot-from-2021-09-30-11-59-21.png)

Is it the case?

**Comment by zrothberg** [comment]
Sorry I had been awake far to long when I had written this. The issue is the class namespaces. so Sample doesn't have anything even though they are legal fields. It seems to be an issue with the pydantic plugin which strips those namespaces from models as they don't exist. When I remove the plugin that fixes the issue. It destroys everything else though. Maybe we can make a patch with them to prevent the namespace removal if its a subclasss of Document.

**Comment by Evisolpxe** [comment]
I encountered same issue and it was resolved by disable pydantic plugin.
But the type hints is still invalid.

`Expected type 'dict[ExpressionField | str, Any]', got 'dict[datetime | None, bool]' instead`
