### ISSUE TITLE
[improvement] deleting a document and getting the operation's result

### ISSUE THREAD

**Issue by didmar** [roman-right/beanie#132]
Currently, there is no syntactic sugar for deleting a document and retrieving the deletion result, to know whether the doc existed or not.

```python
result = MyDocument.find_one({...}).delete()
```
This does not work, as `result` is always `None`

The only way to do this for now is to use the Motor API:
```python
deletion: DeleteResult = await MyDocument.get_motor_collection().delete_one({...})
# deletion.deleted_count can be used to know whether a document was deleted or not
```

**Comment by DaveMDS** [comment]
+1

The beanie documentation say that `MyDocument.delete()` should return a `DeleteResult` instance while it always return `None`

IMO this is more like a bug than an improvements, because it is not possible to know if the document has been deleted or not
