### ISSUE TITLE
Distinct method?

### ISSUE THREAD

**Issue by tgrandjean** [roman-right/beanie#133]
Hello,

What a wonderfull work you've done! I'm starting using Beanie with fastapi and I couldn't find anything in the docs or in the code that allow me to use the `db.collection.disctinct` from [mongodb docs](https://docs.mongodb.com/manual/reference/method/db.collection.distinct/).

I'm using the following document:

```python
class Customer(BaseModel):
    name: str
    email: Optional[str]
    # some fields

class Invoice(Document)

   customer: Customer
    # some fields
```

Coming from pymongo, I use `collection.distinct('customer')` to get the list of distinct customers from the collection 'invoices', is there a way to do this (or something equivalent using aggregate and project) with Beanie?

**Comment by nichitag** [comment]
Roman, how about this future?

**Comment by nichitag** [comment]
https://github.com/roman-right/beanie/pull/260
