### ISSUE TITLE
How do i use the beanie operator 'Or'

### ISSUE THREAD

**Issue by ghost** [roman-right/beanie#137]
i am trying to use the beanie operator or to search for a single using based on 2 criteria where only one should be fulfilled
`await Or({User.email == user_identifier}, {User.username == user_identifier})`

**Comment by roman-right** [comment]
Hey!
Sorry for the delay. You should use it inside of the `find()` method. Like:
```python
users = await User.find(Or({User.email == user_identifier}, {User.username == user_identifier})).to_list()
```
