### ISSUE TITLE
VSCode pylance langauge server and its type checker, pyright reports some errors for the code example in doc site

### ISSUE THREAD

**Issue by grimmer0125** [roman-right/beanie#142]
beanie ver.: 1.7.0
os: macOS 11.6, m1 machine
VSCode: 1.60.1
VSCode Python extension: v2021.9.1246542782

1. `Indexed`:  (related to #10, #59, #105) 
```
Illegal type annotation: call expression not allowed Pylance(reportGeneralTypeIssues)
```
2. `"motor_asyncio"` is not a known member of module Pylance(reportGeneralTypeIssues), will be solved by #147

3. `await product.set({Product.name: "Gold bar"})`
a. `"Product"` is not awaitable Pylance(reportGeneralTypeIssues)
b. "set" is not a known member of "None" Pylance(reportOptionalMemberAccess)

Pylance ref:
https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules

To temporarily suppress this errors:
1. within a file, put `# pyright: reportGeneralTypeIssues=warning, reportOptionalMemberAccess=warning`. (or warning-> false) at the top of the file
2. single line:  put this at the end of the line `# type: ignore` (PEP484)

<img width="892" alt="截圖 2021-11-17 下午2 17 53" src="https://user-images.githubusercontent.com/5940941/142242169-ea09a7fa-ecf4-4fb8-93d1-f14fd217be44.png">

**Comment by roman-right** [comment]
Hey @grimmer0125 ,

Good catch. Thank you.

**Comment by pranav-growthx** [comment]
Is there any plan on this if it will be picked up?

There was this PR that was simplifying the types. Not sure if it's still valid 
https://github.com/BeanieODM/beanie/pull/108

**Comment by wookayin** [comment]
This should be reopened (see also #638), please don't kill a good stale issue.

**Comment by staticxterm** [comment]
Hi @wookayin,
I would argue open a new issue describing the issue at hand in details, with a runnable reproducer script (as text!).
For some other missing type annotations or typing issues we track them with the pinned issue: #1050.

**Comment by wookayin** [comment]
Thanks. This issue was the first one that one would encounter after Googling the type warning messages, and it's just closed with any good solutions linked/suggested. (By the way, a reasonable solution would be to use the `Annotated` typing as suggested in #1050 and #762)

Meanwhile I will try to send a PR to update the tutorial and documentation.
