### ISSUE TITLE
[FR] Plan on having beanie distributed via anaconda / conda-forge?

### ISSUE THREAD

**Issue by jeanmonet** [roman-right/beanie#143]
Hi, if my understanding is correct, beanie is available via pypi, but currently not distributed via conda.
Is there any plan to distribute beanie via a conda repo, such as conda-forge? (it would be awesome)
Thanks!

**Comment by roman-right** [comment]
Hey @jeanmonet ,
Sorry for the late reply. 
It is a good question. I'll take a look, how to do it, and will add this to the gh-actions soon. Thank you!
