### ISSUE TITLE
[Question] How to serialise model data id as `id`, not `_id`

### ISSUE THREAD

**Issue by tonybaloney** [roman-right/beanie#144]
Using beanie with FastAPI, there is the automatic id field, but in the JSON data returned by the API, the field is `_id`

```python
class TodoList(Document):
    name: str
    description: Optional[str] = None
    createdDate: Optional[datetime] = None
    updatedDate: Optional[datetime] = None

@app.get("/lists", response_model=List[TodoList])
async def get_lists(
    top: Optional[int] = None, skip: Optional[int] = None
) -> List[TodoList]:
    """
    Get all Todo lists

    Optional arguments:

    - **top**: Number of lists to return
    - **skip**: Number of lists to skip
    """
    query = TodoList.all().skip(skip).limit(top)
    return await query.to_list()

```

returns
```json
[
  {
    "_id": "61958439e0dbd854f5ab9804",
    "name": "Test List 1",
    "description": "My first test list",
    "createdDate": null,
    "updatedDate": null
  },
...
]
```

but I want the ID field to show as `id` in the responses, not `_id`. I've read multiple threads on this and nothing seems to work

**Comment by roman-right** [comment]
Hey Anthony,

You can try `response_model_by_alias` flag:

```python
@app.get("/lists", response_model=List[TodoList], response_model_by_alias=False)
async def get_lists(
    top: Optional[int] = None, skip: Optional[int] = None
) -> List[TodoList]:
    ...
```

I found this option on the page: https://fastapi.tiangolo.com/tutorial/response-model/

**Comment by tonybaloney** [comment]
This worked, thanks!

**Comment by codespresso** [comment]
@roman-right this works but not in the openapi docs. Also [tiangolo](https://github.com/tiangolo) highlights that it is a hackish way and using separate response model is preferred. Problem is passing raw Document instance to a separate model also does not work unless dict() method is used as response
