### ISSUE TITLE
Performance of encoder when updating a document with relevant size

### ISSUE THREAD

**Issue by swelcker** [roman-right/beanie#148]
Before i start, great work! I enjoy using beanie with MongoDB.
I just migrated one project from ArangoDB to MongoDB, mostly for query and search performance.
Projections are a great relief.

I update documents while they run through a kind of pipeline triggered by User interaction.
Mostly we extend a List, Dict or Pydantic Object stored in such a field. There are thousands of entrys in a json structure per field.
Profiling with cProfile/pstats showed that the encoder of beanie sometimes takes 7 to 15 seconds for such an update.
Tested on 8 core 32GB and 16core 128GB Intel and AMD HW. Ubuntu >= 20.10. Python 3.9.
This was not an issue before i switched to Mongo/beanie. I do the update now in a background task but still want to solve the issue.
Looping through each and every single entry in the encoder class, seems to be a little massiv.

Any hint, tips or advice for optimization?
Would be very appreciated

**Comment by roman-right** [comment]
Hey @swelcker ,

Thank you.

Yes, beanie's performance is not very good for the cases with huge docs or with a big amount of them, as it uses python decoder/encoder. And python is not the fastest tool for this. I'm working on this problem.

I'd suggest using update queries everywhere, where it is possible to avoid fetching documents. For example:

Slow:
```python
class Sample(Document):
    num: int
    color: str
    tags: List[str]
    
async def update_color():
    docs = await Sample.find(Sample.num > 10).to_list()
    for doc in docs:
        doc.color = "Red"
        await doc.replace()
```

Fast:
```python
class Sample(Document):
    num: int
    color: str
    tags: List[str]
    
async def update_color():
    docs = await Sample.find(Sample.num > 10).update(Set({Sample.color: "Red"}))
```

If it will not help, you can share your code and I'll try to help with the optimization

**Comment by swelcker** [comment]
Very helpful, indeed update/set is much much faster and works very well also with huge json structures/objects.
Esp. if you update a field which is a pydantic object.

Keep up the great work!
Thank you very much!
