### ISSUE TITLE
Project only the fields that are in our model

### ISSUE THREAD

**Issue by nzsmith1** [roman-right/beanie#16]
First of all, thanks for creating this project, it has been fantastic to work with.  I have a feature request, which I am happy to implement, I would like the find, find_many, find_all to project our model so that we get back only the data we are interested in.

This helps reduce database load.

An example of where we might use this is when we have a database model which hold a whole bunch of data, but we are loading a summary view which only requires 2 or 3 of these fields.

example:

```python
class AnalyticsLabellingTask(Document):
    reported_by: str = Field(...)
    device_id: str = Field(...)
    priming_start_date: datetime = Field(...)
    event_start_date: datetime = Field(...)
    end_date: datetime = Field(...)
    reviewers: List[str] = Field(...)
    comments: List[Comments] = Field(default_factory=list)
    reviewed_events: List[ReviewedEvents] = Field(default_factory=list)
    water_data: List[TimeSeriesData] = Field(...)
    archived: bool = Field(...)

    class Collection:
        name = "AnalyticsLabellingTasks"

class AnalyticsLabellingTasksSummary(Document):
    device_id: str = Field(...)
    event_start_date: datetime = Field(...)
    end_date: datetime = Field(...)
    reported_by: str = Field(...)

    class Collection:
        name = "AnalyticsLabellingTasks"
```

I am happy to implement this, I would do it by updating the find calls:

```python
# get the field list of interest, this could be generated
# at the __init__ stage and be stored in memory to prevent
# having to build this many times

fields = test.__fields__
projection = {}
for name, field in fields.items():
    if field.alias:
        projection[field.alias] = 1
    else:
        projection[name] = 1

cursor = cls.get_motor_collection().find(filter_query, projection, **kwargs)
```

Let me know your thoughts and I can put together a PR next week

**Comment by roman-right** [comment]
Hello Nicholas,

Thank you for your feedback.
Yes, this is a great idea. It will so good if you will implement this.

I still didn't add development guides. If you will need any help with this (like how to test and etc.) you can ask here or in Discord.

Thank you.
