### ISSUE TITLE
Query linked fields 

### ISSUE THREAD

**Issue by joe-fitkey** [roman-right/beanie#165]
Hi there, 

I have two documents a build and a deployment. A deployment has a build parameter that is a Link to a build document. Multiple deployments can be linked to the same build. 

I now have two requirements: 

1. Get a list of all deployments for a build (the build _id is supplied)
2. Get a list of all deployments that have a build where the project_name equals xyz.   

I couldn't find any relevant sections in the docs. 

Is this something Beanie has support for?

**Comment by roman-right** [comment]
Hi @joe-fitkey ,

1. You can find by id with the next query:
```python
from beanie import Document, Link

class Build(Document):
    ...

class Deployment(Document):
    build: Link[Build]
    
...

build_id = "YOUR BUILD ID"
deployments = await Deployment.find({"build.$id": build_id}).to_list()
```

`$` there is not a typo. It uses RefID field type inside. 
I plan to add backward linking and syntax sugar for this find query later.

2. Unfortunately, this is possible with lookup aggregations only for now.
Here is the MongoDB doc for lookups: https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/
Here is the Beanie doc for aggregations: https://roman-right.github.io/beanie/tutorial/aggregation/

Find by fields of the linked documents is one of the most important features to develop for now. It is estimated to be done in 2-3 weeks. I'll inform you here when it will be done.

**Comment by mdgilene** [comment]
Seems like there was an initial go at getting this working recently. But the documented approach doesn't seem to work for me.

Using the above example my code would be something like
```python
Deployment.find(Deployment.build.id == build_id, fetch_links=True)
```

This doesn't seem to work. I've tried what you mentioned as well with the `{"build.$id": build_id}` however this only works if you do NOT specify `fetch_links`

**Comment by gegnew** [comment]
The docs claim that this works but I also find that it does not

**Comment by gegnew** [comment]
Okay, I spent some more time with this, and it does seem to be the case that the documented behavior is not accurate. I am unable to query for a document by the properties of it DbRef, despite this apparently being supported. Any ideas as to why? My setup is basically:

```
# the base classes just define properties shared with the API schema objects

class Device(Document, DeviceBase):
    name: Optional[str] = ""

class Package(Document, PackageBase):
    tracking_number: Indexed(str, unique=True)  # type: ignore
    device: Link[Device]

device_ids = ['id1', 'id2', 'id3']

packages = await Package.
	In(Package.device.id, device_ids), 
	fetch_links=True,
).to_list()

# packages returns []

# I've also tried i.e.:

packages = await Package.
	Package.device.id == 'id1', 
	fetch_links=True,
).to_list()

packages = await Package.
	Package.device.id == Device1.id, 
	fetch_links=True,
).to_list()


packages = await Package.
	Package.device == Device1, 
	fetch_links=True,
).to_list()
```

**Comment by gianpaj** [comment]
same issue here.

This works

```py
app = await App.get(str(app_id))

# check if app exists

query = await QueryDoc.find({ "app.$id": app_id}).to_list(limit)
```

but these don't
```py
query = await QueryDoc.find(QueryDoc.app == app.id).to_list(limit)

query = await QueryDoc.find(QueryDoc.app == app).to_list(limit)
```

**Comment by fredowashere** [comment]
We are having the same issue

**Comment by tansangxtt** [comment]
> We are having the same issue, solved with `chats = await Chat.find(Chat.author.id == PydanticObjectId(user.id), fetch_links=True, nesting_depth=1).to_list()` But you have an error in the docs, with the strings doesn't work: ![image](https://private-user-images.githubusercontent.com/117639221/348224283-3aec246e-3f02-4e58-860b-292350cc13f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTc2NDEsIm5iZiI6MTcyMTExNzM0MSwicGF0aCI6Ii8xMTc2MzkyMjEvMzQ4MjI0MjgzLTNhZWMyNDZlLTNmMDItNGU1OC04NjBiLTI5MjM1MGNjMTNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwODA5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzZkMDM5MGY1MjdkNGUzMDY1NTMzN2I1Y2UwYWJiMTJjNDFhZDE4MTk0MmQzODk0ZWMzYmFiMTI4NDViNWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L953xdJRLeI6HjFdL4U6o7xsG-AB7-L87JbEVH9WSGk)

The same to me, need to use PydanticObjectId to convert the parameter 'id'

**Comment by alexkrytsky** [comment]
@tansangxtt , were you able to filter on nested non-id fields?
I was trying the scenario per documentation (House.window.width) and it didn't work for me either.

**Comment by stopffen** [comment]
Very unfortunate that this is still not working. 

Neither 
await House.find(
    House.door.id == PydanticObjectId("DOOR_ID_HERE")
).to_list()

nor the slightly more Mongo Native syntax are supported

await House.find(
    House.door.ref.id == PydanticObjectId("DOOR_ID_HERE")
).to_list()

**Comment by yasonk** [comment]
@roman-right should probably re-open this. Seems like a regression?

BTW this seems to work for me:
```
deployments = await Deployment.find(Deployment.product ==  DBRef("products", product_id)).to_list()
```
