### ISSUE TITLE
[Bug] Encrypted Binary fields resulting in Binary type with default subtype instead of user defined subtype.

### ISSUE THREAD

**Issue by UtkarshMish** [roman-right/beanie#166]
Hi ,
I have noticed with one of my projects that storing the data in bson Binary (using encrypted fields,binary subtype = 6) results in data getting stored as Binary with default subtype(subtype=0).

I checked and found that,  it is due to the Encoder Class treating the Binary type as instance of bytes, and converting it into Binary and as the default subtype is 0, it is taking subtype as 0.

Edit: Added PR https://github.com/roman-right/beanie/pull/167

**Comment by roman-right** [comment]
Hi,
Oh wow. This guy is critical. 
Thank you. I'll take a look this evening
