### ISSUE TITLE
Avoid race condition 

### ISSUE THREAD

**Issue by Tobi-De** [roman-right/beanie#169]
Hi, before I start, great work, I started using beanie yesterday with fastapi and I'm really enjoying myself.  I'm building a simple payment API and have a background task that updates the payment status.  I want to prevent a payment from being updated by two processes concurrently which can lead to data loss, I found the revision section in the doc and tried it.  It works fine, an exception is thrown when a local copy tries to update the object, but I don't know where to go from there.  I feel like I need to refresh the database object before any update, is there a way to do this with beanie?

**Comment by roman-right** [comment]
Hey @Tobi-De ,

You mean to update previously inserted documents that didn't use revision, right? To do this you can do smth like:

```python
docs = await Sample.all().to_list()  # here could be any find query instead
for doc in docs:
    doc.revision_id = uuid4()
    await doc.replace(ignore_revision=True)
```

If I misunderstood you, pls clarify your question a little.

Thank you :-)

**Comment by Tobi-De** [comment]
@roman-right Looking a your code it seems I don't quite undestand the revision system. My goal is to avoid concurrent update, somewhere in my code I have something like this ```python```

**Comment by Tobi-De** [comment]
@roman-right Looking a your code it seems I don't quite undestand the revision system. My goal is to avoid concurrent update, somewhere in my code I have something like this 
```python
async def some_background_task():
        .....
       await payment.replace()
       .......
```

and at some occasions (when I'm using `revision=True` on the model settings) I get an exception telling me that a concurrent operation has already update the object (something similar, can't remember the exact verbs), I'm not sure what to do from there. If I do `ignore_revision = True`  doesn't that mean I'm just forcing update and potentially updating the object with old data ?. What I wanted was a way to  lock the resource while it was being updated like in relational database. Sorry I feel like I can't explain myself well and I don't really understand what the revision_id is for, I didn't even think it could be updated manually

**Comment by roman-right** [comment]
So, it depends on the situation. If you already stored some documents and only after that you turned this setting on, it will try to check the revision id for the already stored docs, which don't have revision_id. It will not find it - and will raise an error. To update db data to be able to work with revisions, you need to run the above script once (outside the app), and after it will work well without ignoring flags.

The normal workflow is - Beanie inserts a doc with the generated revision_id. When Beanie tries to update this doc, it checks the revision in the database and in the local doc. If it is the same, it updates the data in the database and creates a new revision id there. Each time it automatically stores a new revision id. If local and db revisions are different - it will not update data but will raise an exception.

**Comment by Tobi-De** [comment]
Thanks @roman-right I have a better undestanding on how revision works now. For the last part where it raise an exception where the local and db revisions are different, I guess I have no way of knowing which data is the most up to date, I need to write some custom logic to identify what changes I need to make.
