### ISSUE TITLE
Add support for synchronous operations

### ISSUE THREAD

**Issue by leynier** [roman-right/beanie#173]
In some contexts, synchronous operations are required but in others, asynchronous operations are possible and more efficient. For example a CLI with [Typer](https://github.com/tiangolo/typer) and a RestAPI with [FastAPI](https://github.com/tiangolo/fastapi).

It would be nice to be able from the same code base to use both synchronous and asynchronous operations using [PyMongo](https://github.com/mongodb/mongo-python-driver/) or [Motor](https://github.com/mongodb/motor) depending on the case.

These are some repositories that can help and projects where a similar idea has been applied:

- https://github.com/python-trio/unasync
- https://github.com/leynier/unasync-cli
- https://github.com/supabase-community/gotrue-py

**Comment by whophil** [comment]
I'm interested in this as well. I am coming from [umongo](https://github.com/Scille/umongo) which supports synchronous and async, but I only use it synchronously.

I'm interested in beanie because I'd like to try pydantic, but having to run it async is a bit of a burden for my applications.

My synchronous use case might not be an aim of the project, but I just wanted to mention it.

**Comment by roman-right** [comment]
I thought about PyMongo support, but Beanie uses async generators inside, and this is too tricky to support and sync and async generators depending on the driver. Probably, later I'll refactor it the way when it will support both, but for now, it is not in the todo. Did you try `unasync` and others? I didn't but did hear that it works well.

**Comment by guesswh0** [comment]
It would be great to see this feature! 
An alternative [ODMantic](https://github.com/art049/odmantic) support both sync (pymongo) and async (motor) engines.

**Comment by mikeckennedy** [comment]
Hey @roman-right With the release of the sync API, can you close this one out?

**Comment by roman-right** [comment]
Thank you @mikeckennedy, you are right.

**Comment by roman-right** [comment]
The sync version is available since `1.13.0`. Here are the migration instructions: https://beanie-odm.dev/tutorial/sync/migrate-from-async/
