### ISSUE TITLE
Add ignore cache in query

### ISSUE THREAD

**Issue by ZebcoWeb** [roman-right/beanie#176]
Cache capability in the database is very efficient, but sometimes it is necessary to use new data. 
I suggest adding the cache ignore attr to queries that are responsible for reading data.

examples of this concept:

`Document.find(ignore_cache=True)`
or
`Document.find().clear_cache()`

**Comment by roman-right** [comment]
Hey @ZebcoWeb 

the first interface is implemented (I forgot to doc it, sorry). It works right the way, you mentioned.
The second one is a very important feature. I'll implement it asap.

Thank you!

**Comment by ZebcoWeb** [comment]
> Hey @ZebcoWeb
> 
> the first interface is implemented (I forgot to doc it, sorry). It works right the way, you mentioned. The second one is a very important feature. I'll implement it asap.
> 
> Thank you!
