### ISSUE TITLE
Support for MongoDB Views

### ISSUE THREAD

**Issue by assemmarwan** [roman-right/beanie#182]
I have a pipeline that involves multi stages. I recentely got to learn about [_views_](https://docs.mongodb.com/v4.0/core/views/) and how by just creating a view in the DB, and calling the view as if it's a collection like below in JS:

```js
db.collection("GroupByMonthView").find()
```

I'm trying to imitate that in Python, however, when I set that collection name as the view, pymogo complains that the target is a view and not a collection.
```
pymongo.errors.OperationFailure: Namespace test_db.GroupByMonth is a view, not a collection, full error: SON([('ok', 0.0), ('errmsg', 'Namespace test_db.GroupByMonth is a view, not a collection'), ('code', 166), ('codeName', 'CommandNotSupportedOnView')])
```

If you would assist me with the way to implement it. If it's not supported, is there a way I can access low-level APIs ?

**Comment by roman-right** [comment]
Hey! Sorry for the late response. Views are supported now in Beanie. Here is the doc: https://roman-right.github.io/beanie/tutorial/views/

**Comment by assemmarwan** [comment]
Much appreciated 👍🏻
