### ISSUE TITLE
Can't replace a dict attribute with save_changes

### ISSUE THREAD

**Issue by paul-finary** [roman-right/beanie#184]
Hi,

In my project, I need to completely replace a dict attribute, but when using the state management and `save_changes`, the dict are merged instead of replaced. This is due to the logic in the following block: https://github.com/roman-right/beanie/blob/513865aadcf61f57c4ba921ce58bb0e7671036ee/beanie/odm/documents.py#L958-L968

How can I continue to use the state management, yet be able to override a whole dict attribute ?

Thanks for the help,

**Comment by paul-finary** [comment]
Hi,

Any idea how to replace a whole dict attribute while using the state management ?

Best,

**Comment by roman-right** [comment]
Hey. Sorry for delay and thank you for the PR
