### ISSUE TITLE
Please issue a Changelog with releases 

### ISSUE THREAD

**Issue by tonybaloney** [roman-right/beanie#185]
Please can you add changenotes with releases. its impossible to know what was shipped in the last update.

If you create the release on GitHub, use the "Auto-generate release notes" button to create one automatically from all the PRs that have been merged since the last release.

**Comment by paul-finary** [comment]
You can find the changelog in docs/changelog.md: https://github.com/roman-right/beanie/blob/main/docs/changelog.md
