### ISSUE TITLE
Pytest Reccomendations

### ISSUE THREAD

**Issue by khan-de-code** [roman-right/beanie#188]
I've been looking for a way to implement a full test of my code that uses beanie and have stumbled across `mongomock_motor`, but unfortunately it does not play well with delete requests as beanie is expecting a generator to `yield from`, while `mongomock_motor` provides the mock delete in the form of a co-routine.

Would you have any insight into how I might go about implementing a mock connection for beanie to utilize? Is there something that exists already that you are aware of or a method to circumvent the need to `init_beanie` with a mock database connection?

**Comment by roman-right** [comment]
Hey!
Sorry for the delay.

I always suggest using a real database for tests, as only a real database works as it should to. To make it simple you can up a docker image with an empty database and use fixtures to fill it with the test data. This way you can test your code not only locally, but using docker image in the gh actions or any other ci/cd you use.

This opinion is based on my experience when mocks didn't catch some corner cases and the app worked wrong as the result.
