### ISSUE TITLE
Replacing Get Database for AsyncIOMotorClient

### ISSUE THREAD

**Issue by folt** [roman-right/beanie#189]
I'm browsing trying to understand how the library works inside. I came across this code:  
https://github.com/roman-right/beanie/blob/ab0cf83346f630e1fa78d3614cc52ba26f96aab7/beanie/odm/utils/general.py#L61-L64

Maybe it makes sense to use the [AsyncIOMotorClient.get_default_database()](https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_client.html?highlight=get_default_database#motor.motor_asyncio.AsyncIOMotorClient.get_default_database) method to get the database from the configuration string? This would make it possible to avoid explicitly passing the database name in the?

**Comment by roman-right** [comment]
Hey @folt ,

Good catch. Thank you. It would be much more beautiful and safe.
