### ISSUE TITLE
Upcoming motor 3.0 (& already existing pymongo 4) compatibility?

### ISSUE THREAD

**Issue by jeanmonet** [roman-right/beanie#191]
Hi,
I understand the current version of the `motor` dependency relies on `pymongo` 3.
Since `pymongo` 4 was released for a while now, `motor` 3.0 will be migrated to `pymongo` 4: https://jira.mongodb.org/browse/MOTOR-643

Do you know if migration work will be required for `beanie` to work with `motor` 3.0 (& `pymongo` 4)?

Many thanks

**Comment by roman-right** [comment]
Hey! I don't think there will be a compatibility problem, but even if yes I'll migrate Beanie to motor3 as soon it will be released.

**Comment by jeanmonet** [comment]
Great news, thanks for the information! I'll be patiently waiting for motor 3 to be able to use use beanie on some project that depends on pymongo 4 :)
