### ISSUE TITLE
Support for inserting dictionary that does not have pydantic-like fields

### ISSUE THREAD

**Issue by astrochun** [roman-right/beanie#192]
First, thanks for making `beanie` available to the community!

I've been using primarily `pymongo` for MongoDB interactions, and only recently started to touch `beanie` so apologies if this is a newbie question. I understand that beanie is an ODM and thus the object should be explicitly declared via the `Document` class, as demonstrated in your examples. However, for one of our use cases, we have data from API requests. To be fair, the data schema is complex with some fields that may not be present. The API is Crossref and here's just an example: https://api.crossref.org/works/10.1088/1741-4326/ac30c6

Our mongo DB caches the above data so it's easier to process within our pipeline. I know that use of the `Document` class is to map to the Mongo collection with explicit fields/keys. Is there a way to pass just a dict through `beanie` without explicit field/key requirements?

For reference, the method for insertion with `pymongo` is something like this:

```python
from pymongo import MongoClient
import requests

response = requests.get('https://api.crossref.org/works/10.1088/1741-4326/ac30c6')
client = MongoClient()

client['db_name']['collection_name'].insert_one(response.json())
```

**Comment by roman-right** [comment]
Hey,
Thank you :)
I don't think it is possible without workarounds now.
But it sounds reasonable. Could you please tell, which operations you would like to do with pure dicts? Inserts and finds or smth else? Should it be partially mapped, or mapped in some cases to the Document-based class? 
I mean, which part of Beanie lib would be helpful here? Or do you need Beanie mapped to some collections, but some of them should be independent of it?

**Comment by astrochun** [comment]
After some thought, I ended up with a hacked solution (dumping the JSON response into a Pydantic `data` field that is a `dict`). With [json2pydantic](https://jsontopydantic.com/), I think explicit declaration is straightforward even for very complex models.

I'm closing this suggestion since I think the needs are very low.
