### ISSUE TITLE
Support for allow_disk_use=True

### ISSUE THREAD

**Issue by tomaspozo** [roman-right/beanie#193]
Hello, love the library so far!

We are getting this error in queries with lots of documents: 

`Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed'`

Thats why we have encountered the need of using `allow_disk_use=True` in some `find`/`aggregate` operations. But haven't found the way to pass that option through Beanie.

Currently we are running this intensive tasks directly with pymongo using  [`allow_disk_use=True`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#:~:text=on%20the%20cursor.-,allow_disk_use,-(optional)%3A%20if%20True) 

Is there a way to do this with Beanie?

Thank you!

**Comment by roman-right** [comment]
Hey,

Thank you for this issue.
Unfortunately, this option is not supported yet. But I'll add this to the list of important tasks. I'll inform you when it will be in place (by the end of this week, I think)

**Comment by tomaspozo** [comment]
Amazing, super fast! thank you!

**Comment by roman-right** [comment]
Hey. Sorry for the delay.
This feature will be released soon (tomorrow, I guess).
It is implemented here: https://github.com/roman-right/beanie/pull/214

Unfortunately for aggregations and for the find operations pymongo (and motor) use different parameter names for this (allow_disk_use for find and allowDiskUse for aggregations). And as Beanie uses aggregations inside of find operations for documents with links, it can confuse.
Here is the example:
https://github.com/roman-right/beanie/pull/214/files#diff-ad89a4ad7a6f4d4fd34163ef59709ef32c933609b4a6f0993315e37e709c426cR331-R355

**Comment by roman-right** [comment]
It is available in `1.10.0`
