### ISSUE TITLE
[mypy] missing library stubs or py.typed marker

### ISSUE THREAD

**Issue by qw-in** [roman-right/beanie#194]
Mypy seems to get angry

https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

**Comment by nzsmith1** [comment]
@roman-right I would be happy to pick this ticket up

**Comment by roman-right** [comment]
Hey @qw-in, Thank you for the issue.

@nzsmith1 it would be great! Thank you :)
