### ISSUE TITLE
got ValidationError when project an 'id' field 

### ISSUE THREAD

**Issue by lsaint** [roman-right/beanie#202]
```
class UserView(BaseModel):
    id: str
    username: str

class UserModel(Document):
    username: str
    email: str

u = await UserModel.find_one(UserModel.id == "xxx").project(UserView)
print(u.id)

```

got the error:

```
pydantic.error_wrappers.ValidationError: 1 validation error for UserView
id
  field required (type=value_error.missing)
```

if i set 
`id: Optional[PydanticObjectId] = None`

got ` id = None` in result

**Comment by ZettZet** [comment]
Today I had the same problem. And I found why this happens and how to _solve it_.

The document ID in Mongo is called _id. The first thought is to name the field "_id: PydanticObjectId" in the projection model. But one underscore in Python marks the field as for internal use. Most likely, pydantic does not use such fields for initialization (for the test, I checked on dataclass and it worked; correct if I'm wrong).

Second thought: aliases. And this is the solution. In your case, you can write the following:

```python
from beanie import Document, PydanticObjectId
from pydantic import BaseModel, Field


class UserView(BaseModel):
    id: PydanticObjectId = Field(alias='_id')
    username: str

class UserModel(Document):
    username: str
    email: str
```

And everything will work!

Perhaps it will later be marked as a bug and fixed, or a better "dirty hack" will be offered.

**Comment by lsaint** [comment]
> Today I had the same problem. And I found why this happens and how to _solve it_.
> 
> The document ID in Mongo is called _id. The first thought is to name the field "_id: PydanticObjectId" in the projection model. But one underscore in Python marks the field as for internal use. Most likely, pydantic does not use such fields for initialization (for the test, I checked on dataclass and it worked; correct if I'm wrong).
> 
> Second thought: aliases. And this is the solution. In your case, you can write the following:
> 
> ```python
> from beanie import Document, PydanticObjectId
> from pydantic import BaseModel, Field
> 
> 
> class UserView(BaseModel):
>     id: PydanticObjectId = Field(alias='_id')
>     username: str
> 
> class UserModel(Document):
>     username: str
>     email: str
> ```
> 
> And everything will work!
> 
> Perhaps it will later be marked as a bug and fixed, or a better "dirty hack" will be offered.

thank you. it's a good idea for now. 
In the long run, I prefer this solution #163
