### ISSUE TITLE
beanie 1.9.1 typing ergonomics

### ISSUE THREAD

**Issue by wonjoonSeol-WS** [roman-right/beanie#205]
Hello,

After adding py.typed in 1.9.1 we can no longer use the syntax suggested in the documentation:

```
await Delivery.find_one(Delivery.delivery_id == delivery_id).set(
    {
           Delivery.zone_id: zone_id,
    }
)
```

> error: Dict entry 1 has incompatible type "int": "int"; expected "str": "Any"  [dict-item]

We can workaround this issue by applying casting:

```
await Delivery.find_one(Delivery.delivery_id == delivery_id).set(
    {
           cast(str, Delivery.zone_id): zone_id,
    }
)
```

We would need to cast everywhere like this. 
But PR https://github.com/roman-right/beanie/pull/201 hasn't updated the documentation so I believe this isn't the intended behaviour. 

Furthermore, mypy now also complains on this line: https://github.com/roman-right/beanie/blob/cf848b82e63cf88b9cba84c18aadc209ceab3225/beanie/odm/utils/general.py#L38

Perhaps we would be better off using Iterable:

```
- document_models: List[Union[Type["DocType"], str]] = None,
+ document_models: Iterable[Union[Type["DocType"], str]] = None,
```

I will submit a PR on the latter part but could there be a better way instead of having to add casting on every existing queries?

**Comment by roman-right** [comment]
Hey,
Thank you for the issue. It is definitely a bug. I'll pick this up this week.

**Comment by roman-right** [comment]
If you'll make a PR for the second part, I'll be happy

**Comment by wonjoonSeol-WS** [comment]
I submitted a PR for the second part. 

As for the first part, kindly note that the same issue arise in other functions too:
```
- await Example.find({Example.id: {"$in": ids}}).sort(+Example.id).to_list()
+ await Example.find({Example.id: {"$in": ids}}).sort(+cast(ExpressionField, Example.id)).to_list()
```
