### ISSUE TITLE
Error: Cannot insert datetime.date - 'datetime.date' object is not iterable

### ISSUE THREAD

**Issue by mikeckennedy** [roman-right/beanie#209]
So I'm trying to save an entry that has a `datetime.date` field. I keep getting two errors:

```python
ValueError: [
  TypeError("'datetime.date' object is not iterable"), 
  TypeError('vars() argument must have __dict__ attribute')
]
```

This is very easy to recreate. Just try to insert this mode:

```python
class TestInsert(beanie.Document):
    name: str
    recorded_date: datetime.date
    items: List[object] = pydantic.Field(default_factory=list)

    class Collection:
        name = "test_remove_after"
```

With these values, like this:

```python
async def test_date_insert_async():
    ti = TestInsert(
        name="Test",
        recorded_date=datetime.date.today()
    )
    return await ti.insert()
```

**Comment by roman-right** [comment]
Hey,
Yes, there is no default encoder for the date, as it could be different ways to store it (iso string, bytes, etc.).
You can specify the encoder for this using custom encoder: https://roman-right.github.io/beanie/tutorial/defining-a-document/#encoders

**Comment by mikeckennedy** [comment]
Awesome, thanks! That'll work.

Is there any way to do the reverse? Like we a decoder or with some event. 

I want to put it in the DB as a `datetime.datetime`, but keep it in mem and model as `datetime.date`. Possible?

**Comment by mikeckennedy** [comment]
Hi Roman. I don't think so. I just tried this:

```python
class TestInsert(beanie.Document):
    recorded_date: datetime.date = pydantic.Field(default_factory=datetime.date.today)

    class Collection:
        name = "test_date"
        bson_encoders = {
            datetime.date: lambda dt: dt.date()
        }
```

And when inserting it:

```python
e = TestInsert()
await e.insert()
```

I get the same error:

```
  File "/Users/michaelkennedy/github/talk-python/talk-python-to-me/src/talk_python_to_me_com/venv/lib/python3.10/site-packages/beanie/odm/utils/encoder.py", line 173, in _encode
    raise ValueError(errors)
ValueError: [TypeError("'datetime.date' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

**Comment by roman-right** [comment]
Hey. Sorry for the late response - weird times.
I'll pick this up this week

**Comment by roman-right** [comment]
Hey,

You are using the wrong inner class here. The model settings clas is `Settings`

Try:

```python
class TestInsert(beanie.Document):
    recorded_date: datetime.date = pydantic.Field(default_factory=datetime.date.today)

    class Collection:
        name = "test_date"
        
    class Settings:
        bson_encoders = {
            datetime.date: lambda dt: datetime.datetime(year=dt.year, month=dt.month, day=dt.day, hour=0, minute=0, second=0)
        }
```

I know, that this can confuse, and plan to merge all the settings into the single inner class, but didn't yet.

**Comment by mikeckennedy** [comment]
Ah, thanks. I must have not read the docs carefully enough. :)
