### ISSUE TITLE
Projections won't project ID?

### ISSUE THREAD

**Issue by mikeckennedy** [roman-right/beanie#210]
Maybe I'm doing this wrong, but it seems I can't get the underlying ObjectID _id back from MongoDB into a projected query. Consider the following projection (_view_):

```python
class GuestNameIdPictureView(pydantic.BaseModel):
    id: PydanticObjectId
    guest_id: int
    name: str
    picture_url: Optional[str]
```

Projecting back this full model:

```python
class Guest(beanie.Document):
    guest_id: int
    name: str
    links: Optional[str]
    picture_url: Optional[str]
    bio: Optional[str]
```

The collection has the _id from `beanie.Document`. But when doing the projection, like this:

```python
guests = await Guest.find().project(GuestNameIdPictureView).sort(-Guest.name).to_list()
```

I get the error:

```python
pydantic.error_wrappers.ValidationError: 1 validation error for GuestNameIdPictureView
id
  field required (type=value_error.missing)
```

**Comment by ZettZet** [comment]
Duplicate #202

**Comment by lsaint** [comment]
#202

**Comment by roman-right** [comment]
Hey!
MongoDB uses "_id" for the id field. But Pydantic thinks that each field, starting with an underscore is private. The solution is or alias as in the @ZettZet answer. Or you can set the custom projection rule:

```python
class GuestNameIdPictureView(pydantic.BaseModel):
    id: PydanticObjectId
    guest_id: int
    name: str
    picture_url: Optional[str]

    class Settings:
        projection = {"id": "$_id"}
```

**Comment by mikeckennedy** [comment]
Thank you all. I decided the alias was cleanest. And that fixed me right up.

```python
class GuestNameIdPictureView(pydantic.BaseModel):
    id: PydanticObjectId = Field(alias='_id')
    guest_id: int
    name: str
    picture_url: Optional[str]
```

**Comment by slingshotvfx** [comment]
For anyone finding this in the future, it can be handy to set [populate_by_name](https://docs.pydantic.dev/2.5/api/config/#pydantic.config.ConfigDict.populate_by_name) in the `model_config` so that either `id` or `_id` can be used during validation, to avoid validation errors if you need to instantiate the model manually from another Beanie model that uses `id`.

For pydantic v2:

```python
class GuestNameIdPictureView(pydantic.BaseModel):
    id: PydanticObjectId = Field(alias='_id')
    guest_id: int
    name: str
    picture_url: Optional[str]

    model_config = pydantic.ConfigDict(populate_by_name=True)
```
