### ISSUE TITLE
Latest version in pip breaks unit tests

### ISSUE THREAD

**Issue by cypherlou** [roman-right/beanie#217]
## production version number
I don't see any specific documentation in your repo related to version numbers, version management or version number conventions - so I'm not sure if my `pip install --upgrade beanie` which took me to version `1.10.0` from `1.18.12` is a production version or not - your website suggests it might well still be `1.8.12`.

## stack
An upgrade to `1.10.0` appears to break a number of my unit tests. I am using `beanie`, `motor`, `mongomock` and `mongomock-motor`.

## question
Is `1.10.0` expected to be a production version or any closely related variants thereof or is this still a work in progress? Presumably it is or it wouldn't be on `pip`.

## production
The upgrade does not appear to break anything talking to the database, so I suspect the issue is with `mongomock` or `mongomock-motor`.

**Comment by roman-right** [comment]
Hey. Sorry for the late response.
I suppose the problem is on the mock side. I'll pick this up soon.
