### ISSUE TITLE
relations don't get populated

### ISSUE THREAD

**Issue by susahin80** [roman-right/beanie#220]
I have a Photo document:

```
class Photo(Document):
    query: str                      
    description: str
    thumb_url: str
    small_url: str
    user_id: PydanticObjectId
    likes: Optional[int]
```

and in Gallery document I reference photos as a list of link like this:
```
class Gallery(Document):
    name: str
    user_id: PydanticObjectId
    photos: Optional[List[Link[Photo]]] =[]
```

I want to get a gallery and linked photos with the following query:
`galleries = await Gallery.find(Gallery.user_id == user_id,fetch_links=True).to_list()`

But in the result I see no photos although the gallery has 2 photos.
```
[
  {
    "_id": "6228f7eb475cc151ad738884",
    "name": "Gallery 1",
    "user_id": "6227967d2f6e63ada3873022",
    "photos": []
  }
]
```
So how can I retrieve the photos of the gallery?

**Comment by activated-coal** [comment]
If you look at the docs, you can only do one of three relations right now:
1. direct, e.g. `field: Link[THING]`
2. optional direct, e.g. `field: Optional[Link[THING]]`
3. list of direct, e.g. `field: List[Link[THING]]`

So, you can't in the current version. 

But also per the docs, this is where one would file an issue to extend functionality.. so wait, I suppose? I would recommend in the meantime, just change your schema to `photos: List[Link[Photo]]] = []` so you don't have to wait for a future version.

**Comment by susahin80** [comment]
@activated-coal I already tried     `photos: List[Link[Photo]] =[]`

My Photo and Gallery documents are like this:

![image](https://user-images.githubusercontent.com/6958551/157838798-d5cbb2a2-a71d-4c0f-aa2c-8714e499246f.png)

![image](https://user-images.githubusercontent.com/6958551/157838858-f342d463-2272-49f4-96e4-565b1c866ff1.png)

**Comment by ktolga** [comment]
> I have a Photo document:
> 
> ```
> class Photo(Document):
>     query: str                      
>     description: str
>     thumb_url: str
>     small_url: str
>     user_id: PydanticObjectId
>     likes: Optional[int]
> ```
> 
> and in Gallery document I reference photos as a list of link like this:
> 
> ```
> class Gallery(Document):
>     name: str
>     user_id: PydanticObjectId
>     photos: Optional[List[Link[Photo]]] =[]
> ```
> 
> I want to get a gallery and linked photos with the following query: `galleries = await Gallery.find(Gallery.user_id == user_id,fetch_links=True).to_list()`
> 
> But in the result I see no photos although the gallery has 2 photos.
> 
> ```
> [
>   {
>     "_id": "6228f7eb475cc151ad738884",
>     "name": "Gallery 1",
>     "user_id": "6227967d2f6e63ada3873022",
>     "photos": []
>   }
> ]
> ```
> 
> So how can I retrieve the photos of the gallery?

In this case i suggest you to use "fetch on demand". Follow the code below;
`        ret_val: T = await self.generic_type.get(id)
        if ret_val:
            await ret_val.fetch_all_links()
`

**Comment by susahin80** [comment]
@ktolga thanks for the suggestion, but I don't want to on demand.

**Comment by roman-right** [comment]
Hey. Sorry for the late reply. Do you need help with this or it was fixed?
