### ISSUE TITLE
Implement `Delete` action event handler

### ISSUE THREAD

**Issue by mdgilene** [roman-right/beanie#225]
Events exist for the basic Insert/Update events. Main event missing is the `Delete` event. This would be useful for executing a variety of cleanup actions after an instance is deleted.

**Comment by roman-right** [comment]
Hey!
Hm, I do agree. I'll check if it will not conflict with any other code and will add this soon.

**Comment by roman-right** [comment]
It is available in the `1.10.3`. Docs will be updated soon too
