### ISSUE TITLE
Missing `findOneAndUpdate()` implementation

### ISSUE THREAD

**Issue by PATAPOsha** [roman-right/beanie#231]
https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndUpdate/
https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndReplace/

Any chance to add it soon? Along with bulk support.

**Comment by leng-yue** [comment]
Any update on this issue?

**Comment by hamilton-earthscope** [comment]
I just stumbled across this issue, and upon further investigation, this is possible using

```py
MyModel.find_one(...).update(..., response_type=UpdateResponse.NEW_DOCUMENT)
```

Docs: https://beanie-odm.dev/tutorial/updating-%26-deleting/#response-type

**Comment by yousafsabir** [comment]
hi @hamilton-earthscope, from where do we import UpdateResponse enum?
Thanks
