### ISSUE TITLE
Activating validate_on_save without defining id field errors

### ISSUE THREAD

**Issue by infinityredux** [roman-right/beanie#236]
Creating a document without defining an `id` field, appears to generate the following error during save (of a new document) when `validate_on_save` is true in the settings.

```
E   pydantic.error_wrappers.ValidationError: 1 validation error for TestDocument
E   id
E     none is not an allowed value (type=type_error.none.not_allowed)
```

Don't think it's directly relevant, but additional context: the document is defined as an extension of an existing pydantic model, so we don't duplicate the common field definitions; also not defining an Id field, since we won't ever directly be using it with this data and want to let the db handle it.

Likely related to #202 but different error / circumstances, so creating new issue.

**Comment by roman-right** [comment]
Hey. It sounds weird. I'll take a look this week. Potentially this is a bug. I'll let you know about the results
