### ISSUE TITLE
How to customize the primary key field in Beanie?

### ISSUE THREAD

**Issue by A-kirami** [roman-right/beanie#243]
This is a great project, I'm migrating from mongoengine, but I don't know how to deal with situations like this.

```python
import mongoengine as me
from mongoengine import Document

class User(Document):
    uid = me.IntField(primary_key=True)
```

I try to use the following method:

```python
from beanie import Document
from pydantic import Field
class User(Document):
    uid: int = Field(alias="_id")
```

It reports some errors.

```python
user = await User(uid=123456).save()
```
```
Argument missing for parameter "_id" (Pylance)
No parameter named "uid" (Pylance)
```

```python
doc = await User.get(user.uid)
```
```
Argument of type "int" cannot be assigned to parameter "document_id" of type "PydanticObjectId" in function "get"
	"int" is incompatible with "PydanticObjectId" (Pylance)
```

After running, the primary key of the document generated in mongodb is not the value of the parameter `uid`.

At the same time, there will be errors in finding documents through `user.uid`.

So what's the right way?

**Comment by roman-right** [comment]
Hey. Beanie supports only `id` field as a primary for now. I have a task on the todo to support any other.
