### ISSUE TITLE
Loading Extra Fields from Document?

### ISSUE THREAD

**Issue by RobertRosca** [roman-right/beanie#244]
I poked around the code a bit and couldn't find a mention of this.

Pydantic has three settings for extra fields: `ignore`, `allow`, and `forbid`.

`ignore` is set by default, so additional fields not present in the model get discarded, `forbid` makes it so that an exception is raised if unknown fields are passed through, and finally `allow` lets you add in whatever fields you want with no validation (see https://pydantic-docs.helpmanual.io/usage/model_config/#options).

You can set extra fields to `allow`, make a document, add arbitrary fields to it, and then insert it into the database - this all works fine and the additional fields are saved. But I'm not too sure how to tell beanie follow the `extra=Extra.allow` setting, so that it will validate fields which it has information for and just load fields which it does not know about.

Currently even with `extra=Extra.allow` it seems that beanie, when finding documents, behaves as if it was set to `ignore` as it just ignores any fields in the database which are not in the model.

Short example:

```python3
from beanie import Document
from pydantic import Extra


class Sample(Document, extra=Extra.allow):
    num: int
    description: str

sample = Sample(10, "weee")

sample.tasty = True

sample.save()
```

The `tasty` field is saved to the database, this is the entry:

```json
{
  "num": 10,
  "description": "weee",
  "tasty": true
}
```

But loading it again:

```python3
loaded_sample = Sample.get(sample.id)

loaded_sample.tasty

# AttributeError: 'Sample' object has no attribute 'tasty'
```

Does not find the new field. I think it would be nice if when beanie sees that the `extra=Extra.allow` setting in the pydantic model it would load all (non-hidden) fields.

**Comment by roman-right** [comment]
Hey. This is an interesting case. I didn't implement the support of this, and a little surprised that it works partially :D. I'll add this to the todo list to add this feature. Thank you for the catch!

**Comment by RobertRosca** [comment]
Nice! I'm can have a look and do a PR for this if that's okay? Wanted to check if you'd like it as a feature first since I wasn't sure.

Might take me a few days to get my head around the code since I haven't looked into it much, but this is a cool project so I'm happy to do that.

**Comment by roman-right** [comment]
Oh, sorry for the delay. I missed your comment. Yes, sure, it would be great if you'll make a PR

**Comment by RobertRosca** [comment]
No problem :smile: 

I poked around a bit and attempted to implement this in the simplest way I could. Once I figured out why the extra fields were being dropped the change to keep them around was small, but I'm not sure what implications it might have and if you'd be happy with the change.

PR is here with some more details: https://github.com/roman-right/beanie/pull/263
