### ISSUE TITLE
QUESTION: Not able to properly pass beanie document object directly as input to FastAPI post endpoint?

### ISSUE THREAD

**Issue by mbl-95** [roman-right/beanie#247]
When type hinting the input argument for a post request in FastAPI using a beanie document class, the _id field is required to be set when creating an instance of the class. However, I would have expected it to only require the relevant (i.e. all non-optional) fields when posting the data to the endpoint and hence leave the _id field to be set in Mongo. A simple dummy example to illustrate the point:

```
class User(Document):
    name: str
    age: int

@app.post("/create", response_model=User)
async def create_user(user: User):
    await user.create()
    return user
```

Looking at the API docs, I can then see that the following fields are all required:

<img width="1290" alt="Skærmbillede 2022-04-25 kl  15 33 03" src="https://user-images.githubusercontent.com/104368006/165100003-165d3510-6531-4c84-8286-91a64c1dfcc9.png">

However, I do not want to set the _id and I am not sure what the revision_id field is?

**Comment by roman-right** [comment]
Hey,
I'm sure this is more about the rendering of an openapi from the model. I'll work on the fastapi support more soon - will handle this too. But in general, it is not a required field. Please try to make a request without these fields filled, if this will not be allowed, pls let me know.

I think you can set up an explicit config for the openapi rendering there or use a separate view model, as fastapi author recommends.

**Comment by mbl-95** [comment]
> 

Hi Roman, thanks!

It's possible to make the request if you completely remove the "_id" field from the request body and don't send that at all. However, it's not possible if you just leave it in and pass an empty "string". Then I get a pydantic value error with the message "Invalid objectId".

Yes, I could create a seperate view model, and I have done that until now. But it's just not as nice when you have linked documents and want to use the relations feature when creating new documents in the database. Then it would be nice to just have the document class with all the relevant mappings instead of having to create a separate view model and then subsequently build and parse the original document class before doing CRUD operations.

But it would definitely be neat with more documentation and examples for using Beanie with FastAPI as this is a really cool and useful project!

**Comment by mbl-95** [comment]
> > 
> 
> Hi Roman, thanks!
> 
> It's possible to make the request if you completely remove the "_id" field from the request body and don't send that at all. However, it's not possible if you just leave it in and pass an empty "string". Then I get a pydantic value error with the message "Invalid objectId".
> 
> Yes, I could create a seperate view model, and I have done that until now. But it's just not as nice when you have linked documents and want to use the relations feature when creating new documents in the database. Then it would be nice to just have the document class with all the relevant mappings instead of having to create a separate view model and then subsequently build and parse the original document class before doing CRUD operations.
> 
> But it would definitely be neat with more documentation and examples for using Beanie with FastAPI as this is a really cool and useful project!

Follow up question... Let's say I have two objects:


```
class Mother(Document):
     name: str
     age: int
     
     class Collection:
          name = "mothers"
     
 class Child(Document):
      name: str
      age: int
      mother: Link[Mother]
      
      class Collection:
           name = "children"
```

When I then would like to create the child through a post endpoint, I'd like that I can fill out the information for all the fields at once (i.e. name, age, and mother) and then have Beanie do the creation of all the underlying collections, however, I am not really seeing this. Beanie is correctly making the "children" collection and putting in the data from the request, but the "mothers" collection is not being created.

A simple example to illustrate. The following could be a post request:
```
{
    name: "Peter",
    age: 12
    mother: {
         name: "Caroline",
         age: 42
    }
}
```
When I post this through the endpoint, I see the "children" collection being generated with the following in the DB:

```
{
     _id: Some_ObjectId
     name: "Peter"
     age: 12,
     mother: DBRef("mothers", Some_ObjectId)
}
```
But I don't see the "mothers" collection anywhere. The only way I can get it in the database is by calling **await child.mother.create()**, but it would be really neat if Beanie took care of this out of the box. Do you expect support for this at some point or do there already exist a way today to achieve this that I don't know about? 

PS: I am initializing both collections in the same database upon application startup.

**Comment by roman-right** [comment]
Hey! About the last point. You can use another `write rule` for the insert (or save) operation, and it will create mothers too. By default `write_rule` is `WriteRules.DO_NOTHING` but if you'll pass `link_rule=WriteRules.WRITE` there, it will insert (or change, depends on context) linked documents too.

Here is the doc:
https://roman-right.github.io/beanie/tutorial/relations/#write
