### ISSUE TITLE
Does beanie implement atomic updating operations?

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [roman-right/beanie#248]
Hello! I am trying to write RPC service on mongodb queue using [this](https://mongodb.github.io/node-mongodb-native/schema/chapter7/) tutorial. I have found options for searching and updating items in beanie's documentation, but I am not shure that they are atomic as "findAndModify" operation from tutorial.

**Comment by roman-right** [comment]
Hey.
Yes and no :) . 

- It is atomic (for every single document, not for the whole operation, if more than one doc should be changed.
- It uses `.update({find_query}, {update_query})` method of MongoDB under the hood.

update (or updateOne) and findAndModify are equally atomic. The difference is that findAndModify returns the doc without changes that were applied. I didn't read the whole tutorial, but if this point is not required, it will fit.

Here is the info about the atomicity https://www.mongodb.com/docs/manual/core/write-operations-atomicity/

**Comment by vBLFTePebWNi6c** [comment]
Thank you for the reply. Am I understand correctly that calling chain `SomeDocument.find(...).update(...)` is equivalent to `findAndModify` method in terms of concurrency control: another thread can not do the same operation in same time?
And if so, `use_revision = True` is should be used when a document update occurs not in a chain call?

**Comment by roman-right** [comment]
In terms of concurrency control yes. Chaining methods are constructing the query. The request to the database happens as a single shot on the await step only. I mean a chain of any number of methods there will run a single database query.

Revision doesn't work here. Revision is needed to check if the document on the db layer was not changed while the copy of it was processed on the application layer. It implements the optimistic lock pattern. In your example, there are no documents on the application layer - the `.find()` part will not return anything to the application layer there. It will be used to construct the `update` query, as the query builder sees that `find` is not the final chaining method, but there is an `update()` part there.

Sorry for being that verbose :)
