### ISSUE TITLE
Use with multiple databases?

### ISSUE THREAD

**Issue by sayeghr** [roman-right/beanie#249]
Does beanie support multiple databases? I have an application that uses multiple databases to separate the data across clients, but it seems that I need to supply the database upon initialization. Can the database be changed at runtime/dynamically?

Thanks in advance!

**Comment by roman-right** [comment]
Hey! Right now you can only use `init_model` method of the Document class to re-assign it to another database. I'm working on supporting hot-swap there, but I don't know, when it will be implemented, unfortunately.

**Comment by sayeghr** [comment]
Thank you for the quick response. Is there any gotchas or potential issues you think i might run into if I hot-swap using the init_model?

**Comment by aasay** [comment]
I am really interested in this functionality too.  I am working on a few hacks to get it to work, but so far everything I come up I am worried would not be compatible with future versions.

**Comment by cs-satish-mishra** [comment]
@sayeghr  did you try initializing it again and again for each request? how it works? 
I have multiple client databases and using fast API will it cause any runtime issues?

**Comment by aasay** [comment]
I spent a fair amount of time on how to do this.  I did not want to initialize the database every time I needed it so I solved it with a Context Manager.  This seems pretty clean, but you do have to write a little extra code each time.  Here is an example.  I tried to document it through the code, but if you have an issues feel free to reach out.  This will create a database for each customer in the list and create the same collection in each customer.

```
from beanie import init_beanie, Document
from typing import Type
import motor.motor_asyncio
import asyncio


# Test DB Model
class TestDBModel(Document):
    name: str
    description: str


class BeanieContext:
    """
    Asynchronous context manager for working with Beanie
    """
    _instances = {}

    def __init__(self, db_model, id_=None):

        key = f"{id_}{db_model.__name__}"

        if key not in self._instances:
            raise Exception(f"{db_model.__name__} collection was not initialized for id {id_}")

        self.model = self._instances[key]

    def __enter__(self):
        raise Exception(f"This class must be called using async")

    def __exit__(self):
        raise Exception(f"This class must be called using async")

    async def __aenter__(self):
        return self.model

    async def __aexit__(self, exc_type, exc_value, exc_tb):
        if exc_type:
            print(exc_type, exc_value, exc_tb)

    @classmethod
    async def ainit(cls, db_model, id_, client):
        key = f"{id_}{db_model.__name__}"

        if key not in cls._instances:
            cls._instances[key] = type(db_model.__name__, (db_model,), {})

        print(f"Init collection {db_model.__name__} for {id_}")
        await init_beanie(database=client[id_], document_models=[cls._instances[key]])


async def main():
    customers = ['customer1', 'customer2']  # List of unique customer keys
    db_username = 'username'
    db_password = 'password'
    db_host = 'name'
    db_port = '27017'

    # Create a client connection to access the database
    client = motor.motor_asyncio.AsyncIOMotorClient(
        f"mongodb://{db_username}:{db_password}@{db_host}:{db_port}",
        uuidRepresentation="standard"
    )

    # Initialize each customer specific DB Model
    for customer in customers:
        await BeanieContext.ainit(TestDBModel, customer, client)

    # Access the individual databases using a context manager
    async with BeanieContext(TestDBModel, customers[0]) as test_db_model:
        test_db_model: Type[TestDBModel]  # Do this so your type hinting still works
        customer_data = test_db_model(name=f'{customers[0]} Data', description=f'{customers[0]} Description')
        await customer_data.insert()
        print(await test_db_model.find().to_list())

    # Access the individual databases using a context manager
    async with BeanieContext(TestDBModel, customers[1]) as test_db_model:
        test_db_model: Type[TestDBModel]  # Do this so your type hinting still works
        customer_data = test_db_model(name=f'{customers[1]} Data', description=f'{customers[1]} Description')
        await customer_data.insert()
        print(await test_db_model.find().to_list())


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by roman-right** [comment]
Hi. I work on a new initializer class atm. I'll add init without index creation option and db switch there in 1-2 weeks or so. I want to have it in a context manager shape too, but the first version probably will be less rich.

**Comment by Cyclone5** [comment]
Hi, is there any update for this topic?

**Comment by manojkumarragupathi** [comment]
> Hi. I work on a new initializer class atm. I'll add init without index creation option and db switch there in 1-2 weeks or so. I want to have it in a context manager shape too, but the first version probably will be less rich.

Hi, Is this functionality released? If yes, which version of beanie should I use to get the db switch option? Please direct me to some code / doc

**Comment by plaksherie** [comment]
Don't have this feature yet?

**Comment by Nootaku** [comment]
Hi there,
I am also interested in this feature. Is there any update ?

**Comment by yutongp** [comment]
Very much interested to this feature as well ❤️

**Comment by arunkumarp93** [comment]
> Hi. I work on a new initializer class atm. I'll add init without index creation option and db switch there in 1-2 weeks or so. I want to have it in a context manager shape too, but the first version probably will be less rich.

@roman-right is this feature released?

**Comment by rgrenonlkr** [comment]
Hello,

I tweaked the great workaround of @aasay  to use a list of models instead of one.
We also have multi tenant (1 database per account, similar schema) and multi "schema" (control plane, account database, ...)

Following @roman-right response I looked into doc for `Document.init_model` but did not find it...

Without this feature out of the box it feels insecure to use beanie in production

**Comment by chaitanyasharma-sse** [comment]
need multi-tenancy support, any plans for this?
