### ISSUE TITLE
Root types compatibility

### ISSUE THREAD

**Issue by platipo** [roman-right/beanie#254]
I was tying to mess around with discriminated unions, that were introduced in [Pydantic 1.9.0](https://pydantic-docs.helpmanual.io/changelog/#v190-2021-12-31), but I noticed that inheriting from `beanie.Document` breaks the following snippet because root types do not allows for other fields (like `id`):

```python
from typing import Literal, Union
from beanie import Document
from pydantic import BaseModel, Field
 
class CarProduct(BaseModel):
    name: Literal["car"]
    engine: str
 
class BoatProduct(BaseModel):
    name: Literal["boat"]
    length: int
 
class Product(Document):
    __root__: Union[CarProduct, BoatProduct] = Field(..., discriminator="name")
```

here is the error:

```
Traceback (most recent call last):
  File "root_beanie.py", line 18, in <module>
    class Product(Document):
  File "pydantic/main.py", line 247, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 109, in pydantic.main.validate_custom_root_type
ValueError: __root__ cannot be mixed with other fields
```

I'm truly interested in supporting the [Polymorphic Pattern](https://www.mongodb.com/developer/how-to/polymorphic-pattern/), is there any workaround?

**Comment by roman-right** [comment]
Hey!
I'll take a look at why discriminated unions don't work for beanie. I can not estimate for now, when it will be fixed (if will)

About the Polymorphic Pattern. Will this fit your case? https://github.com/roman-right/beanie/blob/feature/views/docs/tutorial/multi-model.md

This will be merged by tomorrow. Here is the PR: https://github.com/roman-right/beanie/pull/253

**Comment by platipo** [comment]
Thanks for your quick reply! Upon further reflection the problem is not between `Document` and with discriminated unions, for example this works:

```python
class EmbeddedProduct(Document):
    subfield: Union[CarProduct, BoatProduct] = Field(..., discriminator="name")
```

but on root types. The issue is that they do not allows other fields to be declared other than `__root__`.

I don't know if supporting them makes sense, feel free to close the issue anytime.

**Comment by platipo** [comment]
> About the Polymorphic Pattern. Will this fit your case? https://github.com/roman-right/beanie/blob/feature/views/docs/tutorial/multi-model.md
> 
> This will be merged by tomorrow. Here is the PR: #253

Very cool feature. I will try it as soon as it is released.

If you have a just a document `_id` and do not know beforehand if it is a `One` or `Two`, do you need to make a query for each object?

**Comment by egelados** [comment]
I m also waiting for the release to test the above. 
Regarding your question , perhaps one approach would be to use an extra model to query documents, comprising all of the properties from all the case specific models and returning the data with exclude_unset=True

(Currently I m using discriminated unions implementing the case specific properties in embedded documents due to the __root__ problem.)

**Comment by roman-right** [comment]
Hey. This feature will be merged a little later this week.

The `root`-problem can not be solved. But I'm adding a special class, which will be used to find documents of all the classes for specific collection and fetch them to the respective document objects. So it will be possible to find and document of a specific class and to find over all the documents in the collection with parsing into the right classes.

**Comment by platipo** [comment]
For the moment I came up with this to overcome my problem:

```python
from typing import Any, Literal, Union
from beanie import Document
from pydantic import BaseModel, Field
 
class CarProduct(BaseModel):
    name: Literal["car"]
    engine: str
 
class BoatProduct(BaseModel):
    name: Literal["boat"]
    length: int

class DocShelf(Document):
   product_type: Dict[str, Any]  # this field is the opaque version of the union
   count: int

class ShelfModel(BaseModel):
   product_type: Union[CarProduct, BoatProduct] = Field(..., discriminator="name")
   count: int

ShelfModel.parse_obj(await DocShelf.find_one())
```

This blocks any type of filter on `Product` attributes but allows for easy efficient retrieving on any other field.

**Comment by roman-right** [comment]
The PR is merged :)
