### ISSUE TITLE
Dictionaries with integer keys are not automatically changed to strings

### ISSUE THREAD

**Issue by gnu-lorien** [roman-right/beanie#255]
The following example cannot insert correctly because the keys for posts are integers. In the case of the python json encoder, it automatically converts integer keys like this to strings. For some reason the bson encoder does not do the same thing.

```
from typing import Dict
from pydantic import Field
from beanie import Document, init_beanie
import asyncio, motor.motor_asyncio

class Post(Document):
    title: str = "A sample post"

class Blog(Document):
    posts: Dict[int, Post] = Field(default_factory=dict)

async def main():
    client = motor.motor_asyncio.AsyncIOMotorClient(...)
    await init_beanie(database=client.sample_db, document_models=[Blog, Post])
    blog = Blog(posts={1: Post(title="Broken by the int")})
    document = await blog.insert()
```

This will result in the following exception:
```
bson.errors.InvalidDocument: documents must have only string keys, key was 1
```

The normal pydantic json doesn't have to do anything special with this because the python json encoder converts any key types into strings automatically.

**Comment by gnu-lorien** [comment]
#256 fixes at least this trivial case in my local testing.

**Comment by roman-right** [comment]
This is an interesting catch. Thank you. I'll take a look to the PR soon
