### ISSUE TITLE
API Documentation Interfaces article not updated

### ISSUE THREAD

**Issue by Itay4** [roman-right/beanie#259]
the article in https://roman-right.github.io/beanie/api-documentation/interfaces is not the same as https://github.com/roman-right/beanie/blob/main/docs/api/interfaces.md

i think this leads to the link from https://roman-right.github.io/beanie/tutorial/aggregation/ to be broken and also the nav bar on the right does not show all sections

**Comment by roman-right** [comment]
Oh, thank you for the catch. Documentation is my weak point :)
I'll fix it soon.
(Hm. I, probably, have to make tests for docs, didn't think about it before)
