### ISSUE TITLE
Dont see object id that is inside another object

### ISSUE THREAD

**Issue by redigaffi** [roman-right/beanie#274]
I have the following code:

```
class PlanetDocument(Document):
    created_at: datetime

    name: str = "Planet"


class UserDocument(Document):
    id: Indexed(str)
    username: Optional[str] = None

    planets: List[PlanetDocument] = []

    class Settings:
        name = "user"

```

When I store a PlanetDocument, I can see it has it's id, but when I store the same planet on the UserDocument planets list the object doesnt has id, I store it in user the following way:

```
user = await UserDocument.get(planet_data.user)

new_planet = PlanetDocument("time", "name")
new_planet = await new_planet.create()

user.planets.append(new_planet)
await user.save()
```

Then I lookup user[0].planets[0] and it has not it's id

**Comment by Salleyi75** [comment]
According to the current documentation on the site 

> Write
The next write methods support relations:
>
>insert(...)
replace(...)
save(...)
To apply the writing method to the linked documents, you should set the respective link_rule parameter

so I don't think the create method supports relations.
follow this example:
```
from typing import List

from beanie import Document, Link

class Window(Document):
    x: int = 10
    y: int = 10


class House(Document):
    name: str
    door: Link[Door]
    windows: List[Link[Window]]


house.windows = [Window(x=100, y=100)]
house.name = "NEW NAME"

# The next call will insert a new window object and replace the house instance with updated data
await house.save(link_rule=WriteRules.WRITE)

# `insert` and `replace` methods will work the same way
```

**Comment by roman-right** [comment]
Hi. Sorry for the late reply.

Pls, try adding the `link_rule` parameter to the `save` method.

Here is the example: https://github.com/roman-right/beanie/blob/main/tests/odm/test_relations.py#L196
