### ISSUE TITLE
Questionable async performance

### ISSUE THREAD

**Issue by wonjoonSeol-WS** [roman-right/beanie#278]
Hello,

I have a questionable asynchronous call performances using Beanie.

For this particular example, I do N calls of _get_payload_ using _asyncio.gather()_

```
In [164]: async def get_payload(zone_id: int) -> DasPayload:
     ...:
     ...:      examples = await Example.find(
     ...:         Example.zone_id == zone_id,
     ...:     ).to_list()
     ...:
```

A single call takes 3.03 ms
```
In [165]: await get_payload(1)
time: 3.03 ms (started: 2022-06-03 04:48:02 +09:00)
```

On the other hand calling 1000 of the very same fucntion takes far longer than my expectation:
```
await asyncio.gather(*[get_payload(1) for _ in range(1000)])
time: 1.56 s (started: 2022-06-03 04:48:14 +09:00)
```

I expected the performance to resemble similar to below:
```
In [187]: async def hello():
     ...:     await asyncio.sleep(1)

In [188]: await hello()
time: 1 s (started: 2022-06-03 04:53:02 +09:00)

In [190]: await asyncio.gather(*[hello() for _ in range(1000)])
time: 1.05 s (started: 2022-06-03 04:53:10 +09:00)
```

Diving it a bit further, 
seems like having greater number of MOTOR_MAX_WORKERS actually decreases performance of a single query.

https://motor.readthedocs.io/en/stable/configuration.html

setting MOTOR_MAX_WORKERS=1 
```
[ins] In [3]: await get_payload(1)
Out[3]: []
time: 24.4 ms (started: 2022-06-03 11:30:41 +09:00)

[ins] In [4]: await asyncio.gather(*[get_payload(1) for _ in range(16)])
Out[4]: [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
time: 62.2 ms (started: 2022-06-03 11:30:44 +09:00)
```

Without MOTOR_MAX_WORKERS settings (using the default value of 5 per CPU)
```
[ins] In [14]: await get_payload(1)
Out[14]: []
time: 26.3 ms (started: 2022-06-03 11:30:13 +09:00)

[ins] In [15]: await asyncio.gather(*[get_payload(1) for _ in range(16)])
Out[15]: [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
time: 96.3 ms (started: 2022-06-03 11:30:14 +09:00)
```

MOTOR_MAX_WORKERS=1  is in fact faster, indicating one with less concurrency is actually faster.

What is going on here? 

Is it due to the fact that the underlying Motor library actually wraps blocking library Pymongo and uses uses thread pool to call pymongo using run_in_executor? https://github.com/mongodb/motor/blob/2f75a4030c6fbf076d5a50d2b0e6a492a5bcaa9c/motor/frameworks/asyncio/__init__.py#L73

Would there be any way to further improve on this performance?
For now, it seems like the performance improvement using async Beanie is rather minimal.

**Comment by wonjoonSeol-WS** [comment]
Found this driver for reference: https://github.com/sakal/aiomongo

**Comment by zrothberg** [comment]
So for some reason they arent actually using asyncio futures..... Probably because that was written 8 years ago... 

The actual advantage to using async in your main thread is that it is not blocked. So for something very short you may not see much if any speedup but if you make the actual calls more complex like downloading a lot of data or slow outbound connection you will see the boost. Because ur not doing any connection checking on the front end connection one of the largest advantage spots is missed by your test. 

But as far as the worker count yea it should probably just be one. Their code doesn't actually make sense unless you have multiple workers above it.
