### ISSUE TITLE
Syntax for finding document not passing flake8

### ISSUE THREAD

**Issue by ponty33** [roman-right/beanie#283]
Hi,
I am trying to search document with a field that is boolean
Code:
```python
plan = await Plan.find_one(Plan.active == True)
```
But flake8 is showing `comparison to True should be 'if cond is True:' or 'if cond:'flake8(E712)`
If I change `==` to `is`, then I won't be able to retrieve document that matches the criteria

**Comment by roman-right** [comment]
Hi,
Yes. This is a bit magical. The `==` was overridden (__eq__ method) to make a query as a result (not bool). `is` is not overridden, as there is no such magic method. I'd suggest adding a skip comment for this line
