### ISSUE TITLE
Beanie for Testing

### ISSUE THREAD

**Issue by agustin-del-pino** [roman-right/beanie#285]
Hello,

This issue is for consult about the possibility to use Beanie with some sort of MongoDB Mock.

Has Beanie a "native" support for testing like a "Client Mock" or something?. Otherwise, can be use Beanie with a MongoDB in memory?.

**Comment by GuyGitzMagen** [comment]
I use [mongomock_motor](https://github.com/michaelkryukov/mongomock_motor) client for testing purposes.
For example:
```
@pytest.fixture(autouse=True)
async def my_fixture():
    client = AsyncMongoMockClient()
    await init_beanie(document_models=[BeanieModel], database=client.get_database(name="db"))
```

**Comment by FeliaDev** [comment]
Oh, GuGitzMagen, you're a God. 
A God, I said.

Thank you so much.

**Comment by cdelacruzpinto** [comment]
I've tried @GuyGitzMagen suggestion and got the following error:

sys:1: RuntimeWarning: coroutine 'my_fixture' was never awaited

I'm using pytest-asyncio and I also tried decorating the tests with @pytest.mark.asyncio.

Could any of you folks let me know how you guys avoided this issue? :-)

Thanks in advance!

**Comment by hd10180** [comment]
when i run pytest i got 
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'tests.odm.models.DocumentTestModel'>

    @classmethod
    def get_settings(cls) -> DocumentSettings:
        """
        Get document settings, which was created on
        the initialization step
    
        :return: DocumentSettings class
        """
        if cls._document_settings is None:
>           raise CollectionWasNotInitialized
E           beanie.exceptions.CollectionWasNotInitialized

beanie/odm/documents.py:779: CollectionWasNotInitialized
______________________ ERROR at setup of test_save _______________________

    @pytest.fixture
    def document_not_inserted():
>       return DocumentTestModel(
            test_int=42,
            test_list=[SubDocument(test_str="foo"), SubDocument(test_str="bar")],
            test_doc=SubDocument(test_str="foobar"),
            test_str="kipasa",
        )

tests/odm/conftest.py:186: 
```

What am I doing wrong or have any suggestions?

**Comment by Yalchin403** [comment]
Did anyone was able to use this setup by passing the session parameter to the beanie query?
