### ISSUE TITLE
No validator found for UnionDoc

### ISSUE THREAD

**Issue by chabErch** [roman-right/beanie#289]
Hi ❤️ 

I have UnionDoc subclass and I want to set this subclass as Link. Something like this:

```python
class MyUnion(UnionDoc):
    pass

class MyClass(Document):
    my_union = Link[MyUnion]

```

But I get an error:
> RuntimeError: no validator found for <class 'MyUnion'>, see `arbitrary_types_allowed` in Config

Is there a way to set link to UnionDoc subclass?

**Comment by roman-right** [comment]
Hey. Unfortunately `UnionDoc` doesn't work with links yet. I plan to support it but have no estimates yet.
