### ISSUE TITLE
Check whether ID existed from Linked Documents

### ISSUE THREAD

**Issue by jovannovarian1117** [roman-right/beanie#298]
How do you check only ID from linked documents? linked document are showed as a dictionary right such as
{ "id": 12344567 , "collection": User}, In my case I just want to get only the ID but since link are not subscription able like dictionary?
Is there any way to just access the ID.

My goal is check whether the linked document contains data with id that I pass through the argument but the issue avoid me to
do so.

Thank you !

**Comment by islam-aymn** [comment]
As I can understand from your explanation, you can filter by id just like this:
```python
houses = await House.find(
    House.door.id == "DOOR_ID_HERE"
).to_list()
``` 
[Source](https://roman-right.github.io/beanie/tutorial/relations/)

or 
```python
houses = await House.find(
    Eq(House.door.id, "DOOR_ID_HERE")
).to_list()
```
or 
```python
houses = await House.find(
    IN("door.$id", ["DOOR_ID_HERE"])
).to_list()
```
***If I am not getting it right 😕, please consider adding an example with the expected output.***
