### ISSUE TITLE
Can we specifiy indexes?

### ISSUE THREAD

**Issue by mikeckennedy** [roman-right/beanie#3]
Nice project, looks promising. Is there (or will there) be a way to specify indexes? Something like what MongoEngine is doing would totally suffice if you want inspiration :)

https://docs.mongoengine.org/guide/defining-documents.html?highlight=index#indexes

**Comment by roman-right** [comment]
Hello Michael,
It is nice to see you here. Thank you for your feedback :-) 
This is a very good topic. I plan to add index support soon. I'm thinking about the interface now.

**Comment by mikeckennedy** [comment]
Excellent, excited to hear. Thanks for considering the feature.

**Comment by mikeckennedy** [comment]
Love the inner class style you chose. Nice one.

**Comment by roman-right** [comment]
Thank you! :-)
