### ISSUE TITLE
Links don't fetch in nested documents

### ISSUE THREAD

**Issue by kpostekk** [roman-right/beanie#301]
For this code snippet:

```python
class PlaylistEntry(BaseModel):
    content: Link[FileRecord]
    some_props: List[str]

class PlaylistAbout(BaseModel):
    name: str
    description: str


class Playlist(Document):
    about: PlaylistAbout
    entries: List[PlaylistEntry] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)
    enabled: bool = False
```

link from `PlaylistEntry` does not populate and returns DBRef instead of documents itself. My guess is that, `fetch_links` affects only root level fields.

How can I help with implementing recursive link fetching?

**Comment by kpostekk** [comment]
Related: #250 #277 #300

**Comment by roman-right** [comment]
Hey! The recursive link fetching is not supported yet as there are some tech problems with it. But I'm working on it. Plan to finish it in September.

**Comment by siddharth21s** [comment]
Any update on this? @roman-right

**Comment by erzzauberer** [comment]
Any update on this? @roman-right
