### ISSUE TITLE
[feature] Custom type encoders

### ISSUE THREAD

**Issue by svaraborut** [roman-right/beanie#302]
Have you considered to allow for custom type encoders? Let me explain.

Pydantic supports custom types. In fact I can implement one classes to overload default types, like in this example:

```python
class SpecialStr(str, BaseType):
    __slots__ = []

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        return cls(v)

    def __repr__(self):
        return f'{self.__class__.__name__}({super().__repr__()})'

    def party(self) -> "SpecialString":
            return SpecialString(f'🥳 {self} 🥳')

class Model(BaseModel):
    value: SpecialStr

m = Model(value='house')
m.value.party()  # '🥳 house 🥳'
```

But this function alone does not give the flexibility to abstract database values. As an example, let's assume I would like to have a type `ImgurUrl` which is used to store cdn links like `https://i.imgur.com/rr7pioJ.png`. Easy to see that the link contains a lot of redundant data and assuming the CDN provider does not change it can be stored as `rr7pioJ.png`. I would like to have the possibility to solve this with just a simple custom type, that isolates this behavior in a single class. Something like this:

```python
class ImgurUrl(str, BaseType):
    __slots__ = []

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        return cls(v)

    @classmethod
    def _from_db(cls, value: str) -> "ImgurUrl":
        return ImgurUrl(f'https://i.imgur.com/{value}')
    
    def _to_db(self) -> str:
        if self.startswith('https://i.imgur.com/'):
            return self[20:]
        else:
            raise RuntimeError(f'ImgurUrl does not contain a Imgur Url')

class Model(Document):
    link: ImgurUrl
```

To achieve this the addition of functions like `_to_db` and `_from_db` is required. The first can be solved by modifyling `beanie.odm.utils.encoder` the second one would need a bit more work in `beanie.odm.utils.parsing`. 

Such functions would allow the implementation of custom behavior at the argument or document level.

**Comment by roman-right** [comment]
Hey. Thank you for the feature request.
This feature looks important. Unfortunately, I can not estimate, when I will pick it up.

PRs for this feature are very welcome :).
