### ISSUE TITLE
Cyclic Relations

### ISSUE THREAD

**Issue by gncs** [roman-right/beanie#304]
Will beanie support cyclic relations soon, or is that not a planned feature?

E.g.,
```python
from beanie import Document


class Employer(Document):
    name: str
    employees: Link['Employee']


class Employee(Document):
    name: str
    employer: Link[Employer]
```

**Comment by roman-right** [comment]
Hey,

I thought about it. Honestly, I have no idea how to resolve it correctly on the database side :) But the feature itself looks interesting. Any PRs or suggestions are welcome

**Comment by ujjwalbe** [comment]
This is what I needed right now, Django ORM have this feature.

**Comment by Vitalium** [comment]
It seems that it should be like this (1:M relation):
```python
class Employer(Document):
    name: str
    employees: list[Link['Employee']] = []


class Employee(Document):
    name: str
    employer: Link[Employer] | None = None
```

But have another use case:
```python
class User(Document):
    referrer: Link['User'] | None = None
    referrals: list[Link['User']] = []
```

In this case User can be (optionally) referred by any other user (only one) and can invite many or 0 referrals. These fields should be synchronized somehow under the hood.

Such a feature implemented in Pony ORM in terms of RDBMS (relational DB). Declaration looks like:
```python
class User(db.Entity):
    referrer = Optional('User')
    referrals = Set('User')
```

Where referrer is real column in DB scheme and referrals is handy ORM managed shortcut that is used to get users list who referred by some User. In Pony all type of relations are required to be declared on both sides on entities. This approach has pros and cons, I'm not sure whether it corresponds mongoDB/pydantic/Beanie paradigm.

**Comment by Vitalium** [comment]
Maybe it will be useful to implement some `BackLink` type, which means that its value is not stored in DB, but it should be linked with `Link` (fun pun 😄) defined on the other Document side.
