### ISSUE TITLE
Collection is only created if indexes is defined in Settings

### ISSUE THREAD

**Issue by paulovitorweb** [roman-right/beanie#315]
In version `1.11.6`, the collection is only created if the `indexes` attribute of the Settings class is set to a list containing at least one index.

**Comment by roman-right** [comment]
Wow. Sounds critical.
Could you pls give a code snippet for this? I can not reproduce, unfortunately.

**Comment by paulovitorweb** [comment]
Sorry, it's not a bug. It so happens that the collection is only visible when there are documents or, in this case, when there are user-defined indexes. It was a misinterpretation on my side.
