### ISSUE TITLE
Update cache once the Document has been modified.

### ISSUE THREAD

**Issue by Luc1412** [roman-right/beanie#316]
Currently the cache just saves query results. Lets check some example. We got an Document which got caching enabled.

```py
doc = await ExampleDoc.get(...)
print(doc.example)  # prints "example"
doc.example = 'example 2'
await doc.save()
doc = await ExampleDoc.get(...)
print(doc.example)  # still prints "example"
```

Once the document has been modified or the document has been deleted/recreated the cache should be updated as it provides outdated data.

**Comment by Iazzetta** [comment]
up
