### ISSUE TITLE
Add support for field encryption

### ISSUE THREAD

**Issue by Luc1412** [roman-right/beanie#320]
MongoDB and motor offer field encryption trough the `motor_asyncio.AsyncIOMotorClientEncryption` which offer a `.encrypt` and `.decrypt` function. 

A possible implementation would be similar to Indexes. Eg. typehinting the field as `Encrpted(str)`. Further configuration like the encryption key, keystore db name, algorithm can be done trough the `Settings` class.

**Comment by ogtega** [comment]
Perhaps a field argument would be better?

Something like:
```
field = Field(encrypted=True)
```

**Comment by ogtega** [comment]
It actually looks like all the setup for the auto-encryption can be done while initializing the driver. So there shouldn't be a need for anything beanie specific to be done. You can read the docs on it to see how it is set up [here](https://pymongo.readthedocs.io/en/stable/examples/encryption.html#automatic-client-side-field-level-encryption).

Unless you're asking for a solution that doesn't require [MongoDB Enterprise Server](https://dochub.mongodb.org/core/install-mongodb-enterprise).

**Comment by Luc1412** [comment]
> Perhaps a field argument would be better?
> 
> Something like:
> 
> ```
> field = Field(encrypted=True)
> ```

I think that this isn't possible, as `Field` is based on pydantic and it doesn't offer such field, except you somehow provide it in the extras. I think the `Encrypted(str)` might be better there.


> Unless you're asking for a solution that doesn't require [MongoDB Enterprise Server](https://dochub.mongodb.org/core/install-mongodb-enterprise).

Yeah I'm asking exactly about Field Encyption, which can be used without the Enterprise Edition.

**Comment by ogtega** [comment]
[Hidden fields](https://github.com/roman-right/beanie/blob/main/beanie/odm/documents.py#L699) use an additional arg for in the Field constructor to populate the fields in a Document's exclude property.

Could do something similar for encryption, where the encoder encrypts fields in `document.encrypted` as BSON binary data somewhere [here](https://github.com/roman-right/beanie/blob/main/beanie/odm/utils/encoder.py#L90). And then decryption could be done when parsing the returned document by checking for the model's encrypted attribute and decrypting all fields with a key and scheme provided when `init_beanie` is called.

The Indexed class is really useful, but I feel the Field attributes are super convenient to understand and implement.

Imagine the code example

```
Indexed(Encrypted(str))
Encrypted(Indexed(str))
```
vs
```
field: str = Field(hidden=True, encrypted=True, index=pymongo.ASCENDING)
```

**Comment by Luc1412** [comment]
up

**Comment by slingshotvfx** [comment]
Just wanted to +1 that this would be a handy feature.

**Comment by ogtega** [comment]
@slingshotvfx I just settled on doing an event trigger that encrypts and decrypts.

```python
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
...

SECRET_KEY = get_settings().wallet_key.encode()
aesgcm = AESGCM(SECRET_KEY)

...
@before_event(Insert)
    def encrypt(self):
        nonce = os.urandom(12)
        self.hex = (
            (nonce + aesgcm.encrypt(nonce, self.hex.encode(), None)).hex().upper()
        )

def decrypt(self) -> str:
        data = bytes.fromhex(self.hex)
        return aesgcm.decrypt(data[:12], data[12:], None).decode()
```

**Comment by slingshotvfx** [comment]
Thanks @ogtega. I ended up implementing something similar in my pydantic model by encrypting the value with a `BeforeValidator` and decrypting it with a `PlainSerializer`.  Seems to work just fine and much simpler than futzing with PyMongo's Explicit Encryption.
