### ISSUE TITLE
[BUG] Mypy:: Type error: base class "Document" defined the type as "Optional[PydanticObjectId]"

### ISSUE THREAD

**Issue by amoallim15** [roman-right/beanie#336]
**Describe the bug**
(error: Incompatible types in assignment (expression has type "UUID", base class "Document" defined the type as "Optional[PydanticObjectId]"))

**To Reproduce**
```python
# Please add a code snippet here, that reproduces the problem completely
from beanie import Document
from uuid import uuid4, UUID

class MembershipDao(Document):
    id: UUID = Field(default_factory=uuid4)
    name: str
```

**Expected behavior**
no errors.
temporary solution:
``` python
from beanie import Document
from uuid import uuid4, UUID

class MembershipDao(Document):
    id: UUID = Field(default_factory=uuid4)  # type: ignore
    name: str
```

**Additional context**
N/A

**Comment by buckldav** [comment]
The `Document` class already has a built in `id` field that is generated when the document is created. It's type is `PydanticObjectId`, which clashes with the `UUID` type that you have. I'd recommend simply getting rid of your own `id` field and use the built-in.

**Comment by Mark90** [comment]
> The `Document` class already has a built in `id` field that is generated when the document is created. It's type is `PydanticObjectId`, which clashes with the `UUID` type that you have. I'd recommend simply getting rid of your own `id` field and use the built-in. Docs: https://roman-right.github.io/beanie/api-documentation/document/

But the docs also mention you can use UUID as id type: https://beanie-odm.dev/tutorial/async/defining-a-document/#id

So maybe the `id: Optional[PydanticObjectId] = None` should be typed such that it allows UUID as well

**Comment by Mark90** [comment]
> > The `Document` class already has a built in `id` field that is generated when the document is created. It's type is `PydanticObjectId`, which clashes with the `UUID` type that you have. I'd recommend simply getting rid of your own `id` field and use the built-in. Docs: https://roman-right.github.io/beanie/api-documentation/document/
> 
> But the docs also mention you can use UUID as id type: https://beanie-odm.dev/tutorial/async/defining-a-document/#id
> 
> So maybe the `id: Optional[PydanticObjectId] = None` should be typed such that it allows UUID as well

More concretely, this would mean changing

`id: Optional[PydanticObjectId] = None`

to

`id: Union[PydanticObjectId, UUID, None] = None`

(+ of course making all the other code ready for this)

Did give this a quick try the other day, it's harder than it looks; so before me (or someone else) take a stab at a PR, it would help knowing if the maintainers agree on the approach :)
