### ISSUE TITLE
[DEV] Black not listed in dev-dependencies

### ISSUE THREAD

**Issue by qw-in** [roman-right/beanie#339]
`pyproject.toml` includes a section for `tool.black` but does not appear to list `black` as a `dev-dependency`?

[I assume this is by mistake via the contributing doc](https://roman-right.github.io/beanie/development/#setting-up-the-development-environment):

> To run commands like pytest or black you have to run them using the virtual environment which contains the dependencies and Beanie. You can do this in two ways, you may run poetry shell to activate the environment for the current shell, or you can run them in a one-off fashion as such poetry run pytest.

Edit: noticed missing mypy too

**Comment by qw-in** [comment]
Oh, fixed by #146

**Comment by roman-right** [comment]
Thx
