### ISSUE TITLE
State management error with decimal.Decimal

### ISSUE THREAD

**Issue by nickleman** [roman-right/beanie#340]
Decimal types get retrieved as a bson Decimal128 type and that is causing a ValueError on retrieval if use_state_management is set to True.

ValueError: [TypeError("'Decimal128' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

**To Reproduce**
```python
class Test(beanie.Document):
    amt: decimal.Decimal
    other_amt: pydantic.condecimal(decimal_places=1, multiple_of=decimal.Decimal("0.5")) = 0
    class Settings:
        name = "amounts"
        use_revision = True
        use_state_management = True

```

It saves fine to the DB and in fact, you can save and retrieve without issue with the use_state_management set to False and then turn it on and it'll fail.

**Comment by roman-right** [comment]
This is interesting. I'll check it soon. Thank you!

**Comment by roman-right** [comment]
Hi @nickleman 
Sorry for the delay. I can not reproduce this. Could you pls check if it still breaks?

**Comment by nickleman** [comment]
I simplified my example, but thinking about it, I'm no longer sure if I tested the simplified example. I'll dig in and do a bit more checking (first I'll update all modules to the latest and verify if I even still have an issue) and get back to you. Sorry about that. I do know I had this issue on my current model and am currently working without state management.

**Comment by nickleman** [comment]
Well, with an update to everything, it so far appears to be working now. So, thanks for the fix. :)

**Comment by nickleman** [comment]
Well, Roman, sorry, it had been so long since I looked at this, I forgot to switch back to save_changes() instead of save() on the model. It is still broken for my complex model. I'll see if I can reproduce on the simplified version momentarily.

**Comment by nickleman** [comment]
OK, I chased this down a bit more and figured out if you add class Config: validate_assignment = True tothe class that is what causes the issue on save_changes(). See below full example...:

`import asyncio
import decimal

import beanie
import motor.motor_asyncio
import pydantic
import pymongo


class Test(beanie.Document):
    amt: decimal.Decimal
    other_amt: pydantic.condecimal(
        decimal_places=1, multiple_of=decimal.Decimal("0.5")
    ) = 0

    class Config:
        validate_assignment = True

    class Settings:
        name = "amounts"
        use_revision = True
        use_state_management = True
        indexes = [
            pymongo.IndexModel(keys=[("amt", pymongo.ASCENDING)], name="amt_ascending"),
            pymongo.IndexModel(
                keys=[("other_amt", pymongo.DESCENDING)], name="other_amt_descending"
            ),
        ]


async def init_db(database_url: str, database_name: str) -> None:
    db_client = motor.motor_asyncio.AsyncIOMotorClient(database_url)
    await beanie.init_beanie(db_client[database_name], document_models=[Test])


async def main():
    await init_db(
        "mongodb+srv://test:REDACTED@cluster0.arzc19v.mongodb.net/test_db?retryWrites=true&w=majority",
        "test_db",
    )

    test_amts = Test(amt=1, other_amt=2)
    await test_amts.insert()

    test_amts.amt = 6
    await test_amts.save_changes()

    test_amts = (await Test.find_all().to_list())[0]
    test_amts.other_amt = 7
    await test_amts.save_changes()


if __name__ == "__main__":
    asyncio.run(main())
`

**Comment by roman-right** [comment]
Sorry for the delay. In work
