### ISSUE TITLE
Sorting has typing issue [BUG]

### ISSUE THREAD

**Issue by sghosni** [roman-right/beanie#352]
**Describe the bug**
sort function in FindMany class has stated str attribute for sorting query results and although it works for datetime or int types as well it messes with the type checking.

**To Reproduce**
```python
    user_object_list = (
        await user_object.find(user_object.active == True)
        .sort([(user_object.created_at, pymongo.ASCENDING)])
        .to_list()
    )
```

**Expected behavior**
it should declare all supported data types

**Comment by Asafb26** [comment]
the issue is still there

**Comment by guyzmo** [comment]
for whoever comes back here, the solution is to coerce the field argument to `str()`:

```
        .sort([(str(user_object.created_at), pymongo.ASCENDING)])
```

which works, because in the end that's what is really being done, the field is converted to a string at runtime.
