### ISSUE TITLE
Saving a document that has linked child documents (of which some already exist) fails

### ISSUE THREAD

**Issue by pm5k** [roman-right/beanie#367]
## Abstract

When saving a document that has defined other documents as children using `Link`, if some of those children are already present in the database, the operation fails entirely instead of existing objects being ignored.

### Dependencies
```toml
python = "^3.10"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
beanie = "^1.11.11"
motor = "^3.0.0"
```

### Code

I use `# type: ignore` to make `pylance` shut up about partially typed stuff..
<details>
  <summary>[ ../database/bookmarks.py ]</summary>

```py
import time
from typing import Optional

from beanie import Document, Indexed, Link  # type:ignore
from pydantic import BaseModel

from my_project.database.tags import Tag


class Bookmark(Document):
    title: Indexed(str, unique=True)  # type:ignore
    updated: float = time.time() * 1000
    links: list[str]
    tags: Optional[list[Link[Tag]]]

    class Collection:
        name = "bookmarks"

    class Config:  # type:ignore
        schema_extra = {
            "example": {
                "title": "Test Bookmark",
                "links": ["https://youtube.com"],
                "tags": [{"name": "KEKW"}],
            }
        }


class UpdateBookmark(BaseModel):
    title: str
    updated: Optional[float]
    links: Optional[list[str]]
    tags: Optional[list[Link[Tag]]]

    class Config:
        schema_extra = {
            "example": {
                "title": "Test Bookmark",
                "links": ["https://youtube.com"],
                "tags": [{"name": "KEKW"}],
            }
        }

```
</details>

<details>
  <summary>[ ../database/tags.py ]</summary>

```py
from beanie import Document, Indexed  # type:ignore
from pydantic import BaseModel


class Tag(Document):
    name: Indexed(str, unique=True)  # type:ignore

    class Collection:
        name = "bookmark-tags"

    class Config:  # type:ignore
        schema_extra = {
            "example": {
                "name": "Tutorial",
            }
        }

class UpdateTag(BaseModel):
    name: str

    class Config:
        schema_extra = {
            "example": {
                "name": "Tutorial",
            }
        }
```
</details>

<details>
  <summary>[ ../routes/bookmarks.py ]</summary>

```py
...
@router.post(
    "/",
    response_description="Create a bookmark",
    status_code=status.HTTP_201_CREATED,
    response_model=JSONResponse,
)
async def create_bookmark(bookmark: Bookmark = Body(...)):
    await bookmark.save(link_rule=WriteRules.WRITE)  # type: ignore
    return JSONResponse(
        status_code=status.HTTP_201_CREATED,
        status="CREATED",
        message="Bookmark created",
    )

```
</details>

### Error:
```
File "/home/<me>/Projects/.../.../.venv/lib/python3.10/site-packages/pymongo/helpers.py", line 189, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)

pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: <db>.<collection> index: name_1 dup key: { name: "MOAR" }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: <db>.<collection> index: name_1 dup key: { name: "MOAR" }', 'keyPattern': {'name': 1}, 'keyValue': {'name': 'MOAR'}}
```

## Expected Behaviour

I would suggest that there's some bulk-check that identifies what `Tag` objects (in this example) currently exist in the DB before the "commit" happens, and skip those, while inserting one's that do not exist. However I am not 100% certain `save` is the right method to use so if @roman-right can have a look and advise, that would be excellent.

## Additional Notes

I am still not 100% convinced this is a **bug** in the conventional sense, however no method seemed to have been able to achieve this linked behaviour where a parent being saved as a new object would insert new children and skip over existing children.

**Comment by roman-right** [comment]
Hey @pm5k ,
Thank you for the issue. I'll reproduce it and fix or add another one link rule for this case

**Comment by roman-right** [comment]
Hi,
Sorry for the delay. I'm trying to reproduce it, but unfortunately, can not. Could you please provide a 1-module example or pytest module, that I can run and see the problem? Thank you

**Comment by pm5k** [comment]
I think at this stage it's safe to close this. If I run into it again, I will raise another fresh issue.
