### ISSUE TITLE
[BUG] Mypy not validating query with `Link` field

### ISSUE THREAD

**Issue by dlionel** [roman-right/beanie#368]
**Describe the bug**
When making query with related elements, mypy raise an attribut error for related fields. Even a field as obvious as `id` is flagged with an error. 

**To Reproduce**
- Python==3.9.5
- beanie==1.12.0
- mypy==0.982

Create a file: `test_beanie_link.py`

```python
import beanie

class Merchant(beanie.Document): 
    pass

class Review(beanie.Document): 
    merchant: beanie.Link[Merchant]

async def list_reviews()-> None:
    merchant = await Merchant.find_one()
    assert merchant
    Review.find_many(Review.merchant.id == merchant.id)
    review = Review(merchant=merchant)
```
Then run:
```
mypy test_beanie_link.py
```

**Expected behavior**
Expecting mypy to run without issue raised. 

Instead got:
```
test_beanie_link.py:15: error: "Link[Merchant]" has no attribute "id"
test_beanie_link.py:16: error: Argument "merchant" to "Review" has incompatible type "Merchant"; expected "Link[Merchant]"
```

**Additional context**

**Comment by LinuxKernel31** [comment]
There's something wrong with how you structured it.

`Merchant` should have atleast 1 field, `mypy` will detect it because it has no attribute `id` and you're accessing the `id` `Field`.

Also judging by the query you're using, you should be using it this way:
`bar = await Review.find_one(Review.merchant.id == merchant.id)`


```
from typing import Optional
from beanie import Link
from pydantic import Field
import beanie

class Merchant(beanie.Document): 
    id = Field(None, alias="_id")

class Review(beanie.Document): 
    merchant: Optional[Link[Merchant]]

async def list_reviews()-> None:
    merchant = await Merchant.find_one()
    assert merchant
    Review.find_many(Review.merchant.id == merchant.id)
    review = Review(merchant=merchant)
```

Try this one.
