### ISSUE TITLE
[BUG] Using `Indexed` with an `Enum` raises `TypeError("Cannot extend enumerations")`

### ISSUE THREAD

**Issue by IGJAmpere** [roman-right/beanie#381]
**To Reproduce**
```python
from enum import Enum
from beanie import Document, Indexed


class SomeEnum(Enum):
    BAR = "bar"


class Thing(Document): 
    param: Indexed(SomeEnum)

    class Settings: 
        name = "things"
```

**Expected behavior**
That the indexing works correctly just like it does with any other type. 

---

## Workaround
For those who face this same issue, simply utilize the `indexes` attribute in the `Settings` sub-class, as [per documentation](https://beanie-odm.dev/tutorial/indexes-%26-collection-names/).

**Comment by RamonGiovane** [comment]
Thanks for the suggestion, but the link is broken.
I guess the configuration would be like this:
```python
class Settings: 
    name = 'things'
    indexes: ClassVar[list] = [
        pymongo.IndexModel(
            [('param', pymongo.DESCENDING)],
            name='param_index',
        ),
    ]
```
