### ISSUE TITLE
[BUG] count() does not work when querying with fetch_links=True

### ISSUE THREAD

**Issue by marigan** [roman-right/beanie#426]
When a query is based on nested links the count() does not work

```python
from beanie import Document, Link

class User(Document):
    name: str   
    ...

class Project(Document):
    users: List[Link[User]]
    
...

user_name = "YOUR USER NAME"
projects-count = await Project.find({"users.name": user_name}, fetch_links=true).count()
```

I know I can use query through id as described ```...Project.find({"users.$id": user_id"}).count()``` but would be fine to have this working for more complex queries.

**Comment by roman-right** [comment]
Hey @marigan ,
Thank you for the catch. I'll reproduce and fix it asap

**Comment by nikunjjoshi04** [comment]
Facing the same issue

`query = await Tag.find(Tag.user.email == user.email, fetch_links=True).count()`
