### ISSUE TITLE
[BUG] PydanticObjectId Serialization Issue When Beanie is Used With Starlite

### ISSUE THREAD

**Issue by bwhli** [roman-right/beanie#458]
**Describe the bug**

Starlite raises an HTTP 500 error when trying to return a Beanie `Document`. It seems to be due to the `PydanticObjectId` type not being JSON serializable. The issue was discussed [here](https://github.com/starlite-api/starlite/discussions/819) on the Starlite repo. Is this an issue that can be fixed within Beanie, or should it be addressed within Starlite?

**Comment by roman-right** [comment]
Hi @bwhli ,
Thank you for the catch. I'll add the respective tests and fix it soon.

**Comment by bwhli** [comment]
> Hi @bwhli ,
> 
> Thank you for the catch. I'll add the respective tests and fix it soon.

Thank you! I will do some testing with Starlite once it's fixed.

**Comment by roman-right** [comment]
It looks like this is out of my control, as I can not provide any instructions from inside the class to the `json` methods for Starlite

**Comment by gegnew** [comment]
It seems like this is an issue outside of Starlite as well. 

```python
from typing import Any, Dict
from beanie import PydanticObjectId, Document

class NotificationBase(BaseModel):
    data: Dict[str, Any] | None

class Notification(Document, NotificationBase):
    pass

notification_dict = {'to': {'email': None, 'phone': '+6839199684250'},
 'content': {'title': 'UEFkoKVJYDJuOpGFqojM', 'body': 'zVdRmoUNRkghVhQwoeQb'},
 'data': {'cfxcYxWLWssVAvThlaSK': '8d'},
 '_id': '63b2fe0b87a2e556f2cb2831'}
```

```python
>>> b = Notification(notification_dict)
>>> b
Notification(data={'cfxcYxWLWssVAvThlaSK': '8d'}, id=ObjectId('63b2fe0b87a2e556f2cb2831'))

>>> b.dict()
{'data': {'cfxcYxWLWssVAvThlaSK': '8d'},
 'id': ObjectId('63b2fe0b87a2e556f2cb2831')}  # <--- here
```

I'm running into this issue with FastAPI, as I would like to return `id` in a response schema.

**Comment by noaHson86** [comment]
> edit: nvm, this was my mistake, you can ignore everything below
> 
> > It seems like this is an issue outside of Starlite as well.
> 
> ```python
> from typing import Any, Dict
> from beanie import PydanticObjectId, Document
> 
> class NotificationBase(BaseModel):
>     data: Dict[str, Any] | None
> 
> class Notification(Document, NotificationBase):
>     pass
> 
> notification_dict = {'to': {'email': None, 'phone': '+6839199684250'},
>  'content': {'title': 'UEFkoKVJYDJuOpGFqojM', 'body': 'zVdRmoUNRkghVhQwoeQb'},
>  'data': {'cfxcYxWLWssVAvThlaSK': '8d'},
>  '_id': '63b2fe0b87a2e556f2cb2831'}
> ```
> 
> ```python
> >>> b = Notification(**notification_dict)
> >>> b
> Notification(data={'cfxcYxWLWssVAvThlaSK': '8d'}, id=ObjectId('63b2fe0b87a2e556f2cb2831'))
> 
> >>> b.dict()
> {'data': {'cfxcYxWLWssVAvThlaSK': '8d'},
>  'id': ObjectId('63b2fe0b87a2e556f2cb2831')}  # <--- here
> ```
> 
> I'm running into this issue with FastAPI, as I would like to return `id` in a response schema.

fastapi is returning the Documents just fine, no reason to convert them to a dict before as the json-config on how to handle types gets discarded.
