### ISSUE TITLE
[BUG]: Migration not working - It just shows "Building migration list"

### ISSUE THREAD

**Issue by JoelRaymann** [roman-right/beanie#476]
Hi,

The migration is not working in windows 11. I want to migrate from one Model to another model with extra field. I tried with both iterative and free fall - but none of those work. Whenever I run `beanie migrate -uri <connection-string> -db <db-name> -p  <path/to/*_migrate.py> --distance 1  --forward`, it just shows:

```shell
Building migration list
```

and thats it. It just shows "Building migration list" and closes. I even tried removing the `--distance 1` argument but it still doesn't work. please help.

**Environment**
 - OS: Windows 11
 - Python Version: 3.9.x
 - Database: Mongo DB Atlas Free Tier (has 3 replica sets - so transactions will work)

**Reproduce**

The following code is similar to my actual code:

```python
from beanie import Document, free_fall_migration

class OldModel(Document):
    name: str

class NewModel(Document):
    name: str
    new_field: str

class Forward:

    @free_fall_migration(document_models=[OldModel, NewModel])
    async def add_new_field(self, session):
        async for old_data in OldModel.find_all():
            new_data = NewModel(
                **old_data .dict(),
                new_field='yay'
            )
            await new_data.replace(session=session)


class Backward:
    @free_fall_migration(document_models=[OldModel, NewModel])
    async def remove_new_field(self, session):
        async for new_data in NewModel.find_all():

            new_data_dict = new_data.dict()
            new_data_dict.pop('new_field')
            old_data = OldModel(
                **new_data_dict
            )
            await old_data.replace(session=session)
```

**Expected behavior**

The migration to go through and happen.

**Comment by JoelRaymann** [comment]
Hi @roman-right. Thank you so much for this wonderful package. 

Its been more than 2 weeks since I opened this bug. Please help me with this. I need to migrate lot of models and I am not able to proceed due to this bug. Please help.

**Comment by roman-right** [comment]
Hi!
Sorry for the delay. I dnt have a Windows machine, but I dnt see any platform-specific parts there. I've checked the code above with Ubuntu.
Please take a look here: https://github.com/roman-right/migrations_demo
Could you run the commands from readme against this repo to check if the problem still exists?

**Comment by roman-right** [comment]
I assume the problem is that you give the path to the migration file, but not the dir, that contains it. But I'm not sure

**Comment by JoelRaymann** [comment]
Hi @roman-right, It worked. You are right, I gave the path of the migration file instead of the folder. I am extremely sorry for troubling you. Thank you so much for your help.

**Comment by roman-right** [comment]
Great! :)
