### ISSUE TITLE
Support for Link[Model1|Model2]

### ISSUE THREAD

**Issue by sergiobrr** [roman-right/beanie#480]
### Discussed in https://github.com/roman-right/beanie/discussions/479

<div type='discussions-op-text'>

<sup>Originally posted by **sergiobrr** January 29, 2023</sup>
Hi Roman and thank you for your wonderful piece of software.
I'm asking for support of Link than accept two o more models as related documents.
It can be useful for situations when you need to link an address to an Author or a Reader for example do you think it's possible?

Kind regards Sergio</div>

**Comment by Iazzetta** [comment]
But this is possible:

`my_attr: Link[Model1 or Model2]`

**Comment by sergiobrr** [comment]
@Iazzetta lol i didn't tried this.
And do you know what happens with validation, or when you use prefetch_link?

**Comment by sergiobrr** [comment]
@Iazzetta my friend it doesn't works this way, replacing or updating it keep the wrong collection linked.

**Comment by Iazzetta** [comment]
You need specify exactly the possible models or you want to accept any Document?

`my_attr: Link[Document] # accept any beanie document`
or
`my_attr: Link[Any]` # from typing

**Comment by roman-right** [comment]
Hi! Sorry for the delay. I don't see a way to understand, which model should be used to fetch the data for this case. I mean, these models can use different collections. Link fetching is an aggregation pipeline under the hood, that uses lookups against the linked model collection. If there is more than one model there, beanie has to decide, which one to use.
