### ISSUE TITLE
[BUG] how return id instead of _id in fastapi web

### ISSUE THREAD

**Issue by linpan** [roman-right/beanie#487]
![image](https://user-images.githubusercontent.com/6077601/218399072-6e4a551f-8d28-408b-9814-5f0f91e4e75c.png)

**Comment by MegacoderKim** [comment]
In your response model, you can create and `id` field  with an alias to the `_id` field e.g~
```
from beanie.odm.fields import PydanticObjectId

class StudentResponse(BaseModel):
    id : PydanticObectId= Field(alias="_id")
```

**Comment by linpan** [comment]
cool , ready use beanie for my project.

**Comment by linpan** [comment]
from beanie.odm.fields import PydanticObjectId

class StudentResponse(BaseModel):
    id : from beanie.odm.fields import PydanticObjectId

class StudentResponse(BaseModel):
    id : PydanticObjectId= Field(alias="_id")= Field(alias="_id")

**Comment by MegacoderKim** [comment]
Fixed the typo. Have fun :)
