### ISSUE TITLE
[BUG] Serious - beanie doesn't work ANY - Document = Depends()

### ISSUE THREAD

**Issue by innicoder** [roman-right/beanie#494]
**Describe the bug**
On whatever model I use, `Document = Depends()`, the native FastAPI dependency, it breaks and shows the following.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/100089381/219698079-dabb5981-4bd2-4ceb-8632-cb07a70e15c7.png">

**To Reproduce**
```python

from beanie import Document
from fastapi import FastAPI, Depends

app = FastAPI()



class Student(Document):
    name: str
    age: int

@app.get("/")
def read_root(student: Student = Depends()):
    return {"name": student.name, "age": student.age}

```

**Expected behavior**
Not have the ID and args and revision id..

**Comment by roman-right** [comment]
Hi. The id is a part of the Document class. You can make a reduced model and return filtered result based on it. Revision id will be fixed soon, as it is a hidden field.

**Comment by mikeckennedy** [comment]
Hey @innicoder I'm pretty sure @roman-right means something like you'd see in the projection section for a "reduced model":

https://beanie-odm.dev/tutorial/finding-documents/#projections

```python
class ProductShortView(BaseModel):
    name: str
    price: float

chocolates = await Product.find(
    Product.category.name == "Chocolate").project(ProductShortView).to_list()
```

`ProductShortView` is a pure Pydantic model so should work flawlessly with FastAPI in all the ways those models do.
