### ISSUE TITLE
[BUG] Finding document with None argument

### ISSUE THREAD

**Issue by Cyclone5** [roman-right/beanie#499]
**Describe the bug**
When I use the is None statement while finding any document, the code does not work, but if I use the == statement, it works without any problems.

**To Reproduce**
```
class PrivateLesson(Document):
    teacher_id: Indexed(str)
    student_id: str = None
    lesson_name: str
    lesson_price: int
    lesson_date: str

class OnlyLessonDate(BaseModel):
    lesson_date: str
    
lesson_date_list = await PrivateLesson.find(PrivateLesson.lesson_name == lesson_name,
                                                    PrivateLesson.student_id is None,
                                                    PrivateLesson.teacher_id == teacher_id).project(
            OnlyLessonDate).to_list()

```

**Expected behavior**
await PrivateLesson.find(PrivateLesson.lesson_name == lesson_name,
                                                    PrivateLesson.student_id is None,
                                                    PrivateLesson.teacher_id == teacher_id).project(
            OnlyLessonDate).to_list()

When I type is None, I expect it to work.

**Comment by roman-right** [comment]
Hey! I override respective comparison magic methods to make it work, but there is no one for `is` and I have to change the global python behavior for this. Which is too dangerous. You can ask the linter to ignore this line, and use `==` or use more native mongodb notation with dictionary `{PrivateLesson.student_id: None}`

**Comment by Cyclone5** [comment]
thanks for your reply
