### ISSUE TITLE
[BUG] Migration is stuck even though all the documents have been transformed

### ISSUE THREAD

**Issue by prabhumarappan** [roman-right/beanie#501]
**Describe the bug**
Currently, one of our collections has around 60k documents. Running a migration to add one field to all the documents through the iterative migration results in the migration process being stuck. It even ran for 30 minutes but was still stuck. But what was interesting was that all the documents in DB had the updates. 

Even tried setting the `batch_size` to 100. But even in that case, this will take a lot of time.

Tested

**To Reproduce**
```python
class Forward:
    @iterative_migration(document_models=[xyz])
    async def add_to_xyz(
        self, input_document: Oldxyz, output_document: Newxyz
    ):
        output_document.field = Decimal(0.0)
```

**Expected behavior**

**Additional context**

**Comment by jspiro** [comment]
To add to this, we're seeing each document migrated repeatedly (i.e., more than once). It completes the collection and then starts again.

**Comment by jspiro** [comment]
**Theory**
The batching logic calls `replace_many()` in the middle of the `for` loop, causing the cursor on `find_all()` to re-discover the modified documents after all the existing batches are processed. The loop never completes as a result.

**How did this ever work?**
I don't think it did/can.

The default batch size of 10000 may be higher than the number of documents in any migrations to date. It works fine with a batch size larger than the number of documents (i.e., it only executes this function: https://github.com/roman-right/beanie/blob/main/beanie/migrations/controllers/iterative.py#L116).

**Solution**
Create each batch in memory upfront in the loop then execute each batch in a separate loop. Or identify the IDs of all the documents upfront and iterate over that list using the existing code. Also, there should be some progress logging added.

**Comment by harris** [comment]
This is a potential fix: https://github.com/roman-right/beanie/pull/502
