### ISSUE TITLE
beanie not working on vercel [BUG]

### ISSUE THREAD

**Issue by divyam234** [roman-right/beanie#507]
Currently testing this repo https://github.com/Youngestdev/fastapi-mongo on vercel but its throwing error.

`File "/var/task/beanie/odm/queries/find.py", line 234, in __init__
    super(FindMany, self).__init__(document_model=document_model)
  File "/var/task/beanie/odm/queries/find.py", line 84, in __init__
    self.document_model.get_settings().model_settings.bson_encoders
  File "/var/task/beanie/odm/documents.py", line 1144, in get_settings
    raise CollectionWasNotInitialized`

Although its working fine on local environment .

**Comment by lplit** [comment]
Did you manage to fix it @divyam234 ?
