### ISSUE TITLE
[BUG] Impossible to re-create db index

### ISSUE THREAD

**Issue by Phobos-Programmer** [roman-right/beanie#528]
**Describe the bug**
According to init_beanie documentation in the code I can add "init_beanie" allow_index_dropping parameter to resolve db index changes, but when I try to create a new index (added in the model) I can not run server and receive an error of index duplication.

**To Reproduce**
```python
# step 1: run server first with this model to create index from Indexed(str, unique=True)
class Sample(Document):
    name: Indexed(str, unique=True)

# step 2: then update model to create a partial unique index and reboot server to recreate index.
# You will receive error in init_beanie(...) because existing code tries to create index before
# removing already existing one:
class Sample(Document):
    name: str
    status: str = "active" 
    class Settings:
        indexes = [
            IndexModel(
                "name", unique=True, partialFilterExpression("is_active": {"$eq": "active"})
            ),
        ]

await init_beanie(database=client.db_name, document_models=[Sample], allow_index_dropping=True)
```

**Expected behavior**
When you update index in the Document on next server start index should be updated successfuly
**Additional context**
Also, it would be greate to add information about allow_index_dropping argument in https://beanie-odm.dev/ documentation

**Comment by adam-iris** [comment]
I'm still seeing issues with this.

I'm not super familiar with the backend here, but it looks like `index_information` at https://github.com/roman-right/beanie/blob/1.19.2/beanie/odm/utils/init.py#L294 is getting *all* the indexes, not just the one for the document model being worked on. So any index sourced from another document model gets put into `old_indexes` and subsequently dropped. The upshot is that only indexes for the last document model passed into `init_beanie` wind up in the collection.

I'll keep poking around and see if I can come up with a PR around this, but as I said I'm still familiarizing myself with the code so someone else might have a better idea what's going on here.

**Comment by roman-right** [comment]
Hi @adam-iris 
Please open a new issue with a reproducible example.

**Comment by adam-iris** [comment]
Opened #582 -- I realized when working up a reproducible example that this is specific to inherited models which share a single collection
