### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by roman-right** [roman-right/beanie#534]
### Discussed in https://github.com/roman-right/beanie/discussions/532

<div type='discussions-op-text'>

<sup>Originally posted by **N0odlez** April 13, 2023</sup>
Is it possible to have a Soft Delete functionality, or alternatively let me know how to add a Middleware on each database request to check if a field i.e "is_deleted" is equal to 1.

This would be useful as sometimes you dont want to actually delete the whole Document but you need to keep for auditing purposes.</div>

**Comment by alm0ra** [comment]
hey @roman-right 
do you work on this feature?
i am able to open a PR for adding this feature to beanie

**Comment by alm0ra** [comment]
@roman-right helloooo !!!!
