### ISSUE TITLE
[BUG] Timezone-awareness broken in 1.18.0: TypeError when comparing offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by harryrobertwright** [roman-right/beanie#541]
**Describe the bug**
After upgrading from version 1.17.0 to 1.18.0, timezone-aware datetime objects are no longer being respected, leading to a TypeError when comparing offset-naive and offset-aware datetime objects.

**To Reproduce**

```python
class Person(Document):
    date_created: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    async def save(self, *args, **kwargs):
        self.date_created = datetime.now(timezone.utc) + timedelta(days=1)
        await super().save(*args, *kwargs)
```

```python
class TestPerson(IntegrationTestCase):
    async def test_datetime_awareness(self):
        person = await Person().create()
        original_datetime = person.date_created
        await person.save()

        self.assertGreater(person.date_created, original_datetime)
        
# The test passes for version 1.17.0 but fails in 1.18.0
```

**Expected behavior**
The test should pass with both versions (1.17.0 and 1.18.0) since the datetime objects should be timezone-aware and comparable.

**Additional context**
The error traceback:

```
>       self.assertGreater(person.date_created, original_datetime)
E       TypeError: can't compare offset-naive and offset-aware datetimes

app/response/models/tests/response_test.py:203: TypeError
```
This issue appeared after upgrading the library, and it is causing the test to fail in version 1.18.0.

**Comment by sabattle** [comment]
Possibly related to https://github.com/roman-right/beanie/issues/513?

**Comment by harryrobertwright** [comment]
Hey @roman-right - I wondered if there was any more thoughts on this?
