### ISSUE TITLE
[BUG] Impossible to subclass `Link`

### ISSUE THREAD

**Issue by dlionel** [roman-right/beanie#543]
**Describe the bug**
Subclassing the Link class fails.

**To Reproduce**
```python
from beanie import Link, Document
from typing import TypeVar, Optional

T = TypeVar("T")

class MLink(Link[T]):
    doc: Optional[T] = None

class ProductCategory(Document):
    name: str

class Product(Document):
    category: MLink[ProductCategory]

print(Product.get_link_fields())

# []
```

**Expected behavior**
Subclassing the Link class should be allowed. `Product.get_link_fields()` should give the same result with `MLink` as with `Link`

**Additional context**
I believe the issue is coming from this line: https://github.com/roman-right/beanie/blob/2349a4bc2750e2511cd03f9ba940551c9d497849/beanie/odm/utils/relations.py#L22

We can replace `if field.type_ == Link:` by `if issubclass(field.type_, Link):`

**Comment by roman-right** [comment]
Hi,
hm, yes, you are right. Could you please provide a pytest test for your case - I'll add this to the repo and will fix the respective behavior.
