### ISSUE TITLE
@before_event w/set[BUG]

### ISSUE THREAD

**Issue by opaniagu** [roman-right/beanie#547]
I used example:
```code
class TimestampMixin(BaseModel):
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None

    @before_event(Insert)
    def set_created_at(self):
        self.created_at = datetime.utcnow()

    @before_event(Update, Save, SaveChanges, Replace)
    def set_updated_at(self):
        self.updated_at = datetime.utcnow()
```
And then excuted:

```code
product = await Product.get("644465ec0c9c7f6f19dc232a")
await product.set({Product.name: "Gold bar"})
```

The event is lunched, but the field "updated_at" not update.

If I instead used:
```code
await product.save()
```
work fine!

**Comment by sply88** [comment]
There are two different approaches to update documents:
[Saving changes to existing documents](https://beanie-odm.dev/tutorial/updating-%26-deleting/#saving-changes-to-existing-documents) by setting an instance attribute and *then* using `save` or `replace` to push the changes to the database.
Alternatively [Update queries](https://beanie-odm.dev/tutorial/updating-%26-deleting/#update-queries) via `update`, `set` etc. will apply changes directly on the database level and *then* update the application side instance to match the database document.  

In the example `set_updated_at` is correctly executed and temporarily changes the instance attribute `updated_at`.
But `product.set({Product.name: "Gold bar"})` only updates the `name` field in the db and the attribute `updated_at` is reset to None, as this is the state of the db side document (see [code](https://github.com/roman-right/beanie/blob/main/beanie/odm/documents.py#L465).)

So probably not a Bug? However the [Event-based actions](https://beanie-odm.dev/tutorial/event-based-actions/) Documentation could include a hint, that `@before_event(Update)` decorators are not appropriate for methods that alter instance attributes, as this mixes the two update approaches "instance-then-db" and "db-then-instance".

**Comment by opaniagu** [comment]
The explanation is very clear, thank you very much for your time answering.
