### ISSUE TITLE
[BUG] Doc.save throw an error

### ISSUE THREAD

**Issue by FranciscoCabello** [roman-right/beanie#548]
**Describe the bug**
When I try to use the save method throw an error if the document exists.

**To Reproduce**
```python
doc = Document(**data_dict)
await doc.save()
```

**Expected behavior**
Insert or update the document.

**Additional context**

Error message:
![image](https://user-images.githubusercontent.com/53881342/234710349-1904312b-87e1-44d4-baa4-387811b53edc.png)

Traceback:
![image](https://user-images.githubusercontent.com/53881342/234710413-ce5bfc78-0dcb-42ee-a19a-33bcd52d36d7.png)

**Comment by roman-right** [comment]
Hi @FranciscoCabello 

Please, give me the code snippet that reproduces this bug. I can not reproduce. Here is my code:

```python
import asyncio

from motor.motor_asyncio import AsyncIOMotorClient

from beanie import Document, init_beanie


class Person(Document):
    name: str


async def main() -> None:
    cli = AsyncIOMotorClient("mongodb://beanie:beanie@localhost:27017")
    db = cli.test_index_problems
    await init_beanie(
        database=db,
        document_models=[Person],
    )

    await Person.delete_all()

    person = Person(name="John")
    await person.save()

    person.name = "John Doe"
    await person.save()


asyncio.run(main())
```
