### ISSUE TITLE
[BUG] Compatibility Break in Beanie v1.11.8 Causes Unnecessary Database Reads

### ISSUE THREAD

**Issue by wonjoonSeol-WS** [roman-right/beanie#558]
**Describe the bug**
https://github.com/roman-right/beanie/pull/481/files

Description:
The recent update in Beanie v1.11.8 has introduced a compatibility issue with previous versions. Prior to this update, the "skip_sync = True" option was required for set/update operations to avoid synchronization. However, the new version no longer supports this option and raises a DeprecationWarning instead. As a result, the behaviour of the code has changed, leading to unintended consequences in large-scale systems.

To Reproduce:

```python
    class A(Document): 
        a: int
        b: int

    async def test_variable_change(self, db):
        a = await A(a=1, b=1)
        await a.insert()
        a.a = 5
        print(a.a) # 5
        await a.set({
            A.b: 10,   # updating irrelevant field
        })
        print(a.a) # 1  <-

```

In versions prior to 1.11.8, when skip_sync was set to True, the last line of the above example returned A.a == 5. This behavior was expected since "A" was not immediately read after the set operation.

However, the removal of skip_sync in the new version has led to two significant problems in large-scale systems:

1. Additional read operations are now required for every update/set operation, unnecessarily increasing the database load.

2. Many large-scale systems use read replicas, resulting in replication delays from the master. Beanie writes the updated field data to the master database but immediately tries to read from the replica database. Consequently, inconsistent read results may occur, as demonstrated in the example:

```python
a = await A(a=1, b=1).insert()
await a.set({A.b: 2})
print(a.b) # <- "sometimes" 1 or 2 depending whether it reads from the successfully replicated db or not.
```

To mitigate these issues, a NoSyncSet mixin was created to prevent synchronization in all documents. The mixin avoids calling the database again by setting the updated field values directly. However, with the removal of skip_sync, this mixin is no longer effective as it triggers an error and enforces synchronisation with the database.

```python
class NoSyncSet:
    async def set(self, attrs: dict[ExpressionField | str, Any], *args, **kwargs):
        for name, value in attrs.items():
            setattr(self, name, value) <- Since we have this, no need to call from db again.
        await super().set(attrs, skip_sync=True)  # type: ignore[misc]


    class A(NoSyncSet, Document): 
        a: int
        b: int
```

Now we can no longer use the Mixin as skip_sync raises an error and always sync from the database.

**Expected behavior**
To address this bug, two potential solutions could be implemented:

Allow the skip_sync = True option for set/update operations to continue supporting the previous behaviour and avoid unnecessary database reads and addressing the issue of inconsistent read results due to replication lags.

Alternatively, implement a default behaviour of skip_sync = True, ensuring that documents are not immediately read from the database after set/update operations.

These solutions would restore the desired behaviour and prevent the additional load on the database caused by unnecessary reads in large-scale systems.

**Comment by roman-right** [comment]
Hi @wonjoonSeol-WS ,

It doesn't make additional calls to the database. It uses the "find_one_and_update" method instead of the "update_one" method now. This is a native atomic Mongodb operation that can return updated doc in response.

MongoDB doc: https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndUpdate/
Respective line in Beanie: https://github.com/roman-right/beanie/blob/main/beanie/odm/queries/update.py#L315

For sure high load systems should be supported by Beanie. If you will provide a load test that will show a significant change in memory/cpu usage on the MongoDB side or increased querying time, I'll add a way to use "update_one". I made such tests but didn't see any difference regarding resource usage.
