### ISSUE TITLE
[BUG] Session not passed correctly in iterative data migrations

### ISSUE THREAD

**Issue by datamik** [roman-right/beanie#562]
**Describe the bug**
During iterative data migrations, the session is not passed correctly to the replace_many() method within the run() method, and subsequently, to the .delete() method within the replace_many() method. This leads to issues when there is a problem with insertion, data gets deleted and is not rolled back as expected, due to the missing session argument.
```python
# This is the `run()` method
async def run(self, session):
    #...
    all_migration_ops.append(
        self.output_document_model.replace_many(    # Session should be passed here
            documents=output_documents
        )
    )
    await asyncio.gather(*all_migration_ops)
    
# And this is the `replace_many()` method
@classmethod
async def replace_many(
    cls: Type[DocType],
    documents: List[DocType],
    session: Optional[ClientSession] = None,
) -> None:
    #...
    await cls.find(In(cls.id, ids_list), session=session).delete()    # Session is not passed to delete method here
    await cls.insert_many(documents, session=session)
```

**To Reproduce**
To reproduce this problem, during migration, make changes to a document in a way that would be valid for Pydantic validation but not for writing to the database. For instance, an issue might be related to date serialization. Missing "bson_encoders" in Settings class should be enough to reproduce it.
 
**Expected behavior**
The session should be passed to the replace_many() method within the run() method. Additionally, within the replace_many() method, the session should be passed to the delete() method as well. This ensures that if there's an issue with the insertion of documents, the data that was deleted can be rolled back.

**Additional context**
This issue is especially important during data migrations, where the integrity of the data is crucial. The current bug might lead to data loss if not addressed.

**Comment by roman-right** [comment]
Hi @datamik ,

You are right! It will be fixed asap
