### ISSUE TITLE
[BUG] use "find" and [arg "projection"] query , occurs "TypeError"

### ISSUE THREAD

**Issue by zhuxining** [roman-right/beanie#564]
**Describe the bug**
An error occurs when use "find" and [arg "projection"] query

**To Reproduce**
```python
    db_data = await model.Item.find_many(
        {"name": {"$regex": "str"}},
        projection={"name": 1},
    ).to_list()
```
OR

```python
    db_data = await model.Item.find_many(
        {"name": {"$regex": "str"}},
        **{"projection": {"name": 0}},
    ).to_list()
```

**Expected behavior**
item list, no name field

**Additional context**
TypeError: motor.core.AgnosticCollection.find() got multiple values for keyword argument 'projection'

**Comment by roman-right** [comment]
Hi! Projection for Beanie must be a class inherited from Pydantic `BaseModel` as Beanie works with Pydantic objects.

Try this:

```python
class SampleProjection(BaseModel):
    name: str
    
db_data = await model.Item.find_many(
        {"name": {"$regex": "str"}},
        projection=SampleProjection,
    ).to_list()
```

**Comment by zhuxining** [comment]
I try, it seems that still. @roman-right 

Is it possible to support "projection={"name": 1}"? It's just an idea, respect your design.

**Comment by zhuxining** [comment]
我
