### ISSUE TITLE
[BUG]  Fetch_Links & Inheritance dont work if Link not on Parent Class

### ISSUE THREAD

**Issue by mg3146** [roman-right/beanie#572]
Hi,
To avoid a circular import error with Links, I put my "Base_House" in a separate module than houses.py and house_parts.py. [In reality my modules are much larger].  This is now causing an issue whereby, when I use .find() on Base_House (which really is just an abstract class in a sense, it just has the common features with its children classes), fetch_links = True doesn't work.  My guess is, because the Link is not defined on Base_House.   If I search on the children classes on their own, everything works fine. 

```
from beanie import Document, BackLink, Link
from pydantic import Field


# base.py   <--- Separate module to houses.py to avoid circular import error with house_parts.py
class Base_House(Document):
    name: str    

    class Settings:
        is_root = True

# houses.py
class Apartment(Base_House):
    name: str
    door: Link["Door"]    

class House(Base_House):
    name: str
    door: Link["Door"]    
 
    
# house_parts.py
class Door(Document):
    height: int = 2
    width: int = 1
    house: BackLink[Base_House] = Field(original_field="door")


# people
class Person(Document):
    name: str
    house: Link[Base_House]    
    
    
doc = await Person.find_one(with_children = True, fetch_links = True)

doc.door -> Link  # <-- this won't fetch the link, because - I think - no Link on Base_House
```

**Comment by roman-right** [comment]
Hi @mg3146 ,

I think it is the same problem as mentioned here: https://github.com/roman-right/beanie/issues/482
