### ISSUE TITLE
[BUG] Updates on Documents with "BackLink" do not behave as expected.

### ISSUE THREAD

**Issue by hgalytoby** [roman-right/beanie#580]
**Describe the bug**
Several exceptions caused by `BackLink`.

**To Reproduce**
```python
import asyncio
from beanie import init_beanie, Document, BackLink, WriteRules, Link
from beanie.odm.operators.update.general import Set
from motor import motor_asyncio
from pydantic import Field


class Children(Document):
    name: str
    parent: BackLink['Parent'] = Field(original_field='children')

    class Settings:
        name = 'BackLinkChildren'


class Parent(Document):
    children: list[Link[Children]] = Field(default_factory=list)

    class Settings:
        name = 'BackLinkParent'


async def init():
    client = motor_asyncio.AsyncIOMotorClient(
        'mongodb://root:12345678@localhost:27017'
    )
    await init_beanie(
        database=client.Noah,
        document_models=[
            Parent, Children,
        ],
    )


async def step1():
    await init()
    await Parent(children=[Children(name='a'), Children(name='b')]).save(link_rule=WriteRules.WRITE)


async def step2():
    await init()
    parent = await Parent.find_one(fetch_links=True)
    children = parent.children.pop()
    await Children.find(Children.id == children.id).delete()
    parent.children.append(Children(name='c'))
    await parent.save(link_rule=WriteRules.WRITE)


async def step3():
    await init()
    parent = await Parent.find_one(fetch_links=True)
    children = parent.children.pop()
    await Children.find(Children.id == children.id).delete()
    for ch in parent.children:
        ch.parent = None
    parent.children.append(Children(name='c'))
    await parent.save(link_rule=WriteRules.WRITE)


async def step4():
    await init()
    parent = await Parent.find_one(fetch_links=True)
    children = parent.children.pop()
    children.name = 'hello'
    await Children.find_one(Children.id == children.id).upsert(Set(children), on_insert=children)


if __name__ == '__main__':
    asyncio.run(step1())
    # asyncio.run(step2())
    # asyncio.run(step3())
    # asyncio.run(step4())
    ...

```

**Expected behavior**
### step2
My expectation is to have a result in database as  `{children: [{name: 'a'}, {'name': 'c'}]}` after delete the last `Children` of `Parent` and put it into a new `Children` and store it, but the database result is `{children: [{name: 'a'}, {'name': 'b'}, {'name': 'c'}]}`.

### step3 
I set the `BackLink` of `child` to `None` and it does what I expect.

### step4
An error occurs when I use the `upsert` with `BackLink`.

I wonder if there is a better way to implement `step3`?

And are those exceptions bugs or there is an instructions for implementing these functionalities?

**Comment by roman-right** [comment]
Hi! I'm not sure if this will be supported.

You can think of backlinks as projections, where the data sources are the models with links. Therefore, changing the data of the back-linked documents is possible, but altering the number of them or rewriting the field that contains them is a bit tricky.

I believe this is more due to a lack of documentation than a bug. I'll take a look at what I can do here.

**Comment by hgalytoby** [comment]
> Hi! I'm not sure if this will be supported.
> 
> You can think of backlinks as projections, where the data sources are the models with links. Therefore, changing the data of the back-linked documents is possible, but altering the number of them or rewriting the field that contains them is a bit tricky.
> 
> I believe this is more due to a lack of documentation than a bug. I'll take a look at what I can do here.

Okay, I understand. Thank you for your reply.
