### ISSUE TITLE
[BUG] allow_index_dropping doesn't work with multiple inherited document models

### ISSUE THREAD

**Issue by adam-iris** [roman-right/beanie#582]
**Describe the bug**
Inherited document models share a collection, but `allow_index_dropping = True` assumes each model is exclusive to its collection, so it will treat indexes for other child models as old. The result is that only indexes for the last document model passed to `init_beanie` wind up in the collection.

**To Reproduce**

Pytest:

```python
from beanie import Document, Indexed, init_beanie
import pytest


class BaseDocument(Document):
    class Settings:
        name = 'test_index_drop'
        is_root = True


class IndexedModel1(BaseDocument):
    name1: Indexed(str)


class IndexedModel2(BaseDocument):
    name2: Indexed(str)


@pytest.mark.asyncio
async def test_index_nodrop(db):
    """
    This succeeds
    """
    await init_beanie(
        database=db,
        document_models=[
            IndexedModel1,
            IndexedModel2,
        ],
        allow_index_dropping=False,
    )
    index_info = await IndexedModel1.get_motor_collection().index_information()
    assert set(index_info.keys()) == {'_id_', 'name1_1', 'name2_1'}


@pytest.mark.asyncio
async def test_index_drop(db):
    """
    This fails, the index `name1_1` doesn't exist
    """
    await init_beanie(
        database=db,
        document_models=[
            IndexedModel1,
            IndexedModel2,
        ],
        allow_index_dropping=True,
    )
    index_info = await IndexedModel1.get_motor_collection().index_information()
    assert set(index_info.keys()) == {'_id_', 'name1_1', 'name2_1'}
```

**Expected behavior**
Indexes defined by any child class will exist after initialization.

**Comment by roman-right** [comment]
Hi @adam-iris 
Yes, it makes sense. There could be conflicts for indexes as well. I'll think about how to sort it out. The next release will include the option "merge_indexes," which should help in this case.

**Comment by roman-right** [comment]
Hey @adam-iris 
I forgot to reply, sorry.

This feature was implemented. Here is the the usage example: https://github.com/roman-right/beanie/blob/main/tests/odm/models.py#L818-L831

**Comment by adam-iris** [comment]
The `merge_indexes` flag doesn't seem to have any effect in this case -- I'm still seeing only indexes from the last declared class.

If I'm reading the `init_indexes` code right (https://github.com/roman-right/beanie/blob/main/beanie/odm/utils/init.py#L477) it looks like it merges indexes with any ancestor classes, but not with any "sibling" classes that might be inherited from the same root.
