### ISSUE TITLE
Loosen type requirement for `insert_many()`?

### ISSUE THREAD

**Issue by mikeckennedy** [roman-right/beanie#591]
Hey. This is low priority, however, could be worth doing.

On `Document.insert_many` the parameter documents is of type `list[Document]`. Would it be reasonable to make that any iterable of document rather than strictly list? For example, would a tuple or set of documents work?

There are probably other, related methods with the same situation taking a list of documents. For example, on `beanie_init` the models list there is also a list rather than iterable.

**Comment by roman-right** [comment]
Hi @mikeckennedy ,
You are right. I have to make an inspection and replace lists with iterable type

**Comment by mikeckennedy** [comment]
Thanks Roman. I appreciate that. It's no big deal but something that come up as I'm working on the new course. :)

**Comment by roman-right** [comment]
It will be fixed in https://github.com/roman-right/beanie/pull/669
