### ISSUE TITLE
[improvement] Allow overiding of id field for typechecker

### ISSUE THREAD

**Issue by jorants** [roman-right/beanie#60]
MyPy (rightfully) complains when you override the ID fields type in a subclass. I'm not sure if this is fixable, but maybe we could change the default type so everything seems like a subclass?

**Comment by roman-right** [comment]
Yes, I saw this problem too. 
I didn't get your solution. Could you please show an example, how you see this?

**Comment by jorants** [comment]
I am not sure but I believe it will stop complaining if the overriding type would be a subclass of `PydanticObjectId`. Maybe one of these solutions would work:

- Use `typing.TYPE_CHECKING` to define `PydanticObjectId = Any` when type checking. This does however break type checking for the ID field when it is not overridden.
- Use `__instancecheck__` and/or `__subclasscheck__` to always return true, possibly using `TYPE_CHECKING` again if needed.

But they might also break something else.

**Comment by roman-right** [comment]
I see.
Both ways look a little tricky. But probably should to.
I'll research too, how this problem could be solved. If there is no more solution, we will choose one of these guys. Ok?

**Comment by jorants** [comment]
Hey, i took a deep dive into the mypy internals, not fun. The second solution above does not work. The first does but is ugly and stops all typechecking.

It seems a `Protocol` is the best way to go, this allows us to define the minimal interface for the id field when typechecking, and implement the logic+a few more functions when running.
See PEP 544 for protocols, but this works:
```python
from typing import TYPE_CHECKING, Protocol
if TYPE_CHECKING:
    class PydanticObjectId(Protocol):
        #TODO Define expected minimal interface for an id field
        ...
else:
    class PydanticObjectId(ObjectId):
        """
        Object Id field. Compatible with Pydantic.
        """
        
        @classmethod
        def __get_validators__(cls):
            yield cls.validate

        @classmethod
        def validate(cls, v):
            if isinstance(v, bytes):
                v = v.decode("utf-8")
            try:
                return PydanticObjectId(v)
            except InvalidId:
                raise TypeError("Id must be of type PydanticObjectId")

        @classmethod
        def __modify_schema__(cls, field_schema):
            field_schema.update(
                type="string",
                examples=["5eb7cf5a86d9755df3a6c593", "5eb7cfb05e32e07750a1756a"],
            )
```
This allows us to ensure that not everything can be an id, only things which implement some functions we need.

**Comment by roman-right** [comment]
I think I came up with another one solution.
Look:

```python
class Document(BaseModel, UpdateMethods):
    id: Union[PydanticObjectId, Any] = None

    @validator("id")
    def id_validation(cls, v):
        if cls.__fields__["id"].type_ == Union[PydanticObjectId, Any]:
            v = PydanticObjectId(v)
        return v
```

It looks like mypy has no problems with this. The solution is probably not finished, but looks working

**Comment by jorants** [comment]
Maybe a combination would be nice, making an `IdField` protocol and defining `id` as `Union[PydanticObjectId, IdField]` and keeping your validator. `Any` is basically an empty protocol, but this would allow for a minimal mandatory interface for any `id` field.

**Comment by roman-right** [comment]
Tbh, I had no time yesterday to take a look at the Protocol PEP. I plan to read it tomorrow.
But I like, how your solution looks like, yep.

**Comment by jorants** [comment]
Maybe checkout the [mypy docs](https://mypy.readthedocs.io/en/stable/protocols.html) instead, bit shorter and to the point

**Comment by roman-right** [comment]
Sorry for the delay,
I've read the doc about Protocol. Yes, your way looks more native for this problem. I mean, it should work without any extra pydantic validation and will have a clear notation in the model.
Great idea!

**Comment by jorants** [comment]
In principle all id fields should implement a `__get_validators__` function, and maybe more for serialization?
Except build-in types are handled separately.  If we could make a list of built in types that could function as an `id` (or a reasonable subset) then we could do something like 

```python

class IdFieldProtocol(Protocol):
  @classmethod
  def __get_validators__(...): ... # TODO define types correctly  

class PydanticObjectId(ObjectId)L
   ... # as it is now

BuildinIdTypes = Union[int,str,UUID] # or some other buildins as well

IdType = Union[PydanticObjectId,IdFieldProtocol,BuildinIdTypes]

```
Now mypy will complain if you use a type that can not function within pydantic, as it should.
The other option is to simply have an empty protocol, which basically silences mypy in all cases.
