### ISSUE TITLE
[BUG] Not operator cant be on top level

### ISSUE THREAD

**Issue by akriese** [roman-right/beanie#600]
**Describe the bug**
I am getting an error from mongoDB when using the `Not` operator: ```pymongo.errors.OperationFailure: unknown top level operator: $not. If you are trying to negate an entire expression, use $nor., full error: {'ok': 0.0, 'errmsg': 'unknown top level operator: $not. If you are trying to negate an entire expression, use $nor.', 'code': 2, 'codeName': 'BadValue'}```

**To Reproduce**
```python
class User(Document):
    id: PydanticObjectId

User.find(User.id != "...") # this works
User.find(Not(Eq(User.id, "..."))) # does not work 
User.find(Not(User.id == "...")) # does not work either
```

**Expected behavior**
All above snippets should work.

**Additional context**
The query produced by `beanie` is `{"$not": {"price": {"$lt": 10}}}`, according to the mongoDB docs, this should be inverted to `{"price": {"$not": {"$lt": 10}}}`.
I haven't tested this yet. Wanted to wait on if there is a reasoning behind the switch-up :) Maybe this got changed in a recent mongoDB version?

**Comment by roman-right** [comment]
Hi! 
I'll check this soon. As a tmp solution, you can use the Neq operator or !=
Thank you for the catch

**Comment by akriese** [comment]
I'll leave it at the `!=` for now, couldn't find anything about an `Neq` operator :)

**Comment by roman-right** [comment]
This bug is fixed in https://github.com/roman-right/beanie/pull/669. Please try
