### ISSUE TITLE
[BUG] Document.save() does not trigger Insert event even when saving a new document

### ISSUE THREAD

**Issue by Russell-Pollari** [roman-right/beanie#607]
**Describe the bug**
`document.save()` does not trigger an `Insert` event when saving a new document.

Ideally, I can rely on a `before_event(Insert)` to fire any time a new document is created in the database. For example, when setting a `created_at` field (see example)

**To Reproduce**
```python
import asyncio
from datetime import datetime

from motor.motor_asyncio import AsyncIOMotorClient

from beanie import Document, init_beanie, before_event, Insert


class User(Document):
    name: str
    created_at: datetime = None

    @before_event(Insert)
    def set_created_at(self):
        self.created_at = datetime.now()


async def main():
    client = AsyncIOMotorClient("mongodb://localhost:3001/")
    await init_beanie(database=client.test, document_models=[User])
    
    # Saving new document does not trigger Insert action
    user = User(name="John")
    await user.save()
    print(user.created_at)  # None
    
    # user.insert() works as expected
    user = User(name="Jane")
    await user.insert()
    print(user.created_at)  # datetime


if __name__ == "__main__":
    asyncio.run(main())
```

**Expected behavior**
This is contrary to the [docs](https://beanie-odm.dev/tutorial/event-based-actions/)
>save() triggers Insert if it is creating a new document, triggers Replace if it replaces an existing document

I expected `@before_event(Insert)` to fire any time a new document was inserted

**Additional context**
It looks like `save` calls `document.update()` with `upsert=True`, which triggers an `Update` event

At a minimum, the documentation for Event-based actions should be updated

But would be great to have an action run any time a new doc is inserted (with `insert`, or with `update(upsert=True)`)

**Comment by roman-right** [comment]
Hi! Can you please try using the `Save` event in addition to `Insert` in the list of events for the `before_event` decorator

**Comment by Russell-Pollari** [comment]
@roman-right That would trigger the action, but it would also trigger the same action when saving an existing document

For my use case above, I'd only like to set `created_at` on insert.

In my project, I can just stick to intentionally using `document.insert` for new documents. But your documentation around events needs to be updated. Happy to submit a PR

However, looking at the implementation of `document.update()`, it creates a new _id if one is not on the object
```python
        if self.id is not None:
            find_query: Dict[str, Any] = {"_id": self.id}
        else:
            find_query = {"_id": PydanticObjectId()}
```

This find_query with a new objectId will always return nothing, correct? If so, then I think we can call `document.insert()` if there is no `_id` instead of an update with `upsert=True`

Does that make sense? If so, happy to put a PR together

**Comment by roman-right** [comment]
Hi @Russell-Pollari,

I wouldn't use the `insert` method for this case because, even if there is an id, it doesn't guarantee that such an object exists in the database. It could be, for example, a UUID generated by the default factory during object creation. In that case, we would have two different database operations for the same scenario. I prefer to keep it consistent. However, I think it would be nice to handle upsert events. I'm not sure how it is currently possible, but I'll think about it.

Regarding the documentation improvements - yes, sure. It would be great if you could submit a PR.

**Comment by Russell-Pollari** [comment]
> In that case, we would have two different database operations for the same scenario. I prefer to keep it consistent.

Fair point. I'm inclined to agree

> However, I think it would be nice to handle upsert events. I'm not sure how it is currently possible, but I'll think about it.

I will too. I feel like an `After Upsert` event would be do-able, given the response from the db operation. 

But not sure how to go about before upsert, other than first doing a query to determine if the document exists already. Which basically...  makes using `upsert` redundant

**Comment by Russell-Pollari** [comment]
@roman-right 
What about moving towards MongoDB Change Streams as event triggers? 

https://www.mongodb.com/docs/manual/changeStreams/

**Comment by roman-right** [comment]
Change Streams are not supported by Beanie yet. I plan to add them soon. Then, yes, I'll check if it is possible to have events based on them.
