### ISSUE TITLE
[BUG] Inconsistent result type using upsert()

### ISSUE THREAD

**Issue by tito** [roman-right/beanie#611]
**Describe the bug**

Based on the documentation, this code can be used to insert a document in database, or update it if it exist.

```python
await Product.find_one(Product.name == "Tony's").upsert(
    Set({Product.price: 3.33}), 
    on_insert=Product(name="Tony's", price=3.33, category=chocolate)
)
```

The "bug" if i may say is:
- if the document is inserted, it will return a `Product` document
- if the document is updated, it will return a `UpdateResult`

What is the correct approach to always have a document as a result ?
Should we check for UpdateResult, and act accordingly ?

**Expected behavior**
I expected to have a `Product` document.

**Comment by roman-right** [comment]
Hi. Sorry for the delay.
I have to update the doc. The behavior you are talking about is possible now.

```python
from beanie.odm.queries.update import UpdateResponse

await Product.find_one(Product.name == "Tony's").upsert(
    Set({Product.price: 3.33}),
    on_insert=Product(name="Tony's", price=3.33, category=chocolate),
    response_type=UpdateResponse.NEW_DOCUMENT
)
```

I'll update the doc and probably will make this behavior default in a few version with respective warnings.
