### ISSUE TITLE
[BUG] values are not updated in the db after modification in @before_event Save event

### ISSUE THREAD

**Issue by yousafsabir** [roman-right/beanie#613]
**Describe the bug**
I have an Admin model. it has a password field, which needs to be hashed before saving to the db. the password hashing works when I insert a fresh document in the db. but it doesn't work when I update that document.

**To Reproduce**
```python
# ------------------ Admin Model ---------------------

class Admin(Timestamps, Document):
    username: Indexed(str, unique=True)
    password: str
    role: AdminRole
    metadata: Optional[dict]

    @before_event([Insert, Update])
    def hash_password(self):
        self.password = bcrypt.hash(self.password)
        print(self)

    class Settings:
        name = "admins"

# ------------ where I'm updating -----------------------

        admin = await Admin.find_one({"username": username})

        if not admin:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={"message": "Admin doesn't exists"},
            )

        await admin.update({"$set": {"password": password}})

        return admin
```

**Expected behavior**
I printed the self object in the before_event. and before update, it looks like this ( password='thsibisd' )

```python
id=ObjectId('64a3f9c9f4a3032ad0694efd') revision_id=None createdAt=datetime.datetime(2023, 7, 4, 10, 51, 53, 869000) updatedAt=datetime.datetime(2023, 7, 4, 10, 51, 53, 161000) username='yousaf' password='thsibisd' role='ADMIN' metadata=None
```

After I hash the password, it looks like this ( password='$2b$12$jkxEB.o1J28gWaC6OtVSZewe1lTXNbthclSM2JGyBMRK/KZfj1Tq6' )

```python
id=ObjectId('64a3f9c9f4a3032ad0694efd') revision_id=None createdAt=datetime.datetime(2023, 7, 4, 10, 51, 53, 869000) updatedAt=datetime.datetime(2023, 7, 4, 10, 51, 53, 161000) username='yousaf' password='$2b$12$jkxEB.o1J28gWaC6OtVSZewe1lTXNbthclSM2JGyBMRK/KZfj1Tq6' role='ADMIN' metadata=None
```

but when I fetch it again from the db, the the password doesn't change (still password='thsibisd' )

**Comment by sarangBuzzyBrains** [comment]
I am facing the same error, The event based changes are working on insert operations but not working on update operations.

I just took a high level look at **_insert_** and **_update_** method and it looks like **while **_updating_** we are not passing the _'self'_ variable** where these event based changes are made 
Although in **_insert_** method we are passing in **self** variable.

Update Method

>  result = await self.find_one(find_query).update(
                *arguments,
                session=session,
                response_type=UpdateResponse.NEW_DOCUMENT,
                bulk_writer=bulk_writer,
                **pymongo_kwargs,
            )

Insert Method

> result = await self.get_motor_collection().insert_one(
            get_dict(
                self, to_db=True, keep_nulls=self.get_settings().keep_nulls
            ),
            session=session,
        )

cc @roman-right

**Comment by roman-right** [comment]
Hi @yousafsabir,

I see. When you pass `{"$set": {"password": password}}` with the update method, Beanie sends this instruction to the database without applying it to the local document. In your case, I would suggest setting the password using Python syntax first and then using the `save_changes()` method. Additionally, you'll need to add the respective `SaveChanges` event to the list.

```python
admin.password = password
await admin.save_changes()
```

**Comment by roman-right** [comment]
Hi @sarangBuzzyBrains,
Please review the response above. If it does not work for your case, please provide a description of the issue.

**Comment by yousafsabir** [comment]
> Hi @yousafsabir,
> 
> I see. When you pass `{"$set": {"password": password}}` with the update method, Beanie sends this instruction to the database without applying it to the local document. In your case, I would suggest setting the password using Python syntax first and then using the `save_changes()` method. Additionally, you'll need to add the respective `SaveChanges` event to the list.
> 
> ```python
> admin.password = password
> await admin.save_changes()
> ```

Yup, this worked. Thank you for your time 😊

I also had to set state management to true in the model's settings

```python
class Admin(Document):
...
    class Settings:
        name = "admin"
        use_state_management = True
```
