### ISSUE TITLE
[BUG] Query using link field, with fetch_links=False

### ISSUE THREAD

**Issue by alex-linx** [roman-right/beanie#614]
**Describe the bug**
In the docs, it says the following:

Search by linked documents fields
If the fetch_links parameter is set to True, search by linked documents fields is available.

By field of the direct link:
```
houses = await House.find(
    House.door.height == 2,
    fetch_links=True
).to_list()
```
By list of links:
```
houses = await House.find(
    House.windows.x > 10,
    fetch_links=True
).to_list()
```
Search by id of the linked documents works using the following syntax:
```
houses = await House.find(
    House.door.id == "DOOR_ID_HERE"
).to_list()
```

**It works the same way with fetch_links equal to True and False and for find_many and find_one methods.**

**Expected behavior**
From the documentation (specifically the last sentence there in bold), it is implied that I can do the following and get a result

```
houses = await House.find(
    House.windows.x > 10,
    fetch_links=False
).to_list()
```

However, I tried it and it just returns an empty list.
So I think that as a first step the documentation should be updated to specify that in order to query on fields of linked docs you have to set `fetch_links=True`.
And as a feature request, I would like to be able to query on the linked object's field's without actually fetching it, if that makes sense

**Comment by roman-right** [comment]
Hi! Sorry for the confusion. The line `It works the same way with fetch_links equal to True and False and for find_many and find_one methods` pertained to using only ids. I will update the documentation to make it clearer.

Unfortunately, it is impossible to make this feature available without fetching in the current approach I am using. When it doesn't fetch links, it uses find queries. When it does fetch, it employs aggregation pipelines under the hood. To enable searching by fields in the linked documents for all cases, I have to use aggregation pipelines consistently. However, this can potentially reduce performance.

Could you please explain your use case? I can consider how to add new functionality or introduce a new flag to enable such searching for cases like yours.

**Comment by alex-linx** [comment]
Thanks for the update :).
Yeah, I would Imagine that's it's not a trivial thing to implement, especially without hurting performance in the general case.

In this particular case I have a Person Document - that has in it some fields like name, and email, and also a Person can have a manager - who is also a person, so it's a link.
I want to be able to get a person based on a manager's name for example.
In this case I guess it could be somewhat problematic, because from what I've seen if I pass `fetch_links=True` it will also fetch them recursively - so I would get the manager of a manager of a manager etc. - which sounds very inefficient.

In general I think it could be a useful feature in some cases to be able to query a document based on fields of links, without actually fetching the full link. How easy or difficuly it is to implement - that's another question, I'm guessing it could get pretty complicated. I guess the deeper issue here is that mongo doesn't have JOIN as a core concept

**Comment by roman-right** [comment]
Sorry for the late reply,

Yes, searching by the ID of linked docs should work even without prefetching.

Regarding recursive fetching - I don't think `fetch_links=True` will reduce performance too much. It will fetch 2 layers deep only and then stop. And even if I make a solution for this without actual fetching, it will work the same way on the database side using the same aggregation pipeline, but with a projection to remove links. The difference is - the Python app will parse a few more objects. If you don't fetch hundreds of objects, it will have no effect on performance.

**Comment by alex-linx** [comment]
Great! I wasn't aware that there is a limit to the fetch depth.
