### ISSUE TITLE
[BUG] jsonable_encoder fails to convert PydanticObjectId for fastapi version 0.100.0

### ISSUE THREAD

**Issue by siddhesh1981** [roman-right/beanie#621]
**Describe the bug**
For the fastapi version 0.100.0, jsonable_encoder fails to convert PydanticObjectId, and returns it as an empty dictionary. Although, it works in fastapi version 0.92.0. 

**To Reproduce**
```python
#fastapi==0.100.0
#beanie==1.17.0
#pydantic==1.10.11

#model
class Post(Document):
    name: str = Field(..., min_length=2, max_length=200)
    created_at: datetime = datetime.utcnow()
    created_by: PydanticObjectId

#schemas
class PostBase(BaseModel):
    name: str = Field(..., min_length=2, max_length=100)

class PostView(PostBase):
    id: PydanticObjectId = Field(alias='_id')
    created_by: PydanticObjectId
    created_at: datetime 

#retrieve all posts
async def get_all_posts(user: User):
	posts = await Post.find_many({Post.created_by: user.id}).project(PostView).to_list()			
	posts= jsonable_encoder(posts[::-1])
        return posts

```

**Expected behavior**
It will be great if beanie works seamlessly with the latest version of fastapi. I am not able to use the latest version of fastapi because of this error. Is there a better way to solve this issue and make it work with fastapi==0.100.0? 

**Additional context**

**Comment by roman-right** [comment]
Hi @siddhesh1981,

To be compatible with both pydantic v1 and v2, FastAPI has its own `ENCODERS_BY_TYPE` variable that is used in the encoder. Beanie cannot patch it as it does for Pydantic. I'm checking how I can fix this for FastAPI. For now, please use the following code somewhere after importing `init_beanie`:

```python
from fastapi.encoders import ENCODERS_BY_TYPE
from pydantic.json import ENCODERS_BY_TYPE as PYDANTIC_ENCODERS_BY_TYPE
ENCODERS_BY_TYPE.update(PYDANTIC_ENCODERS_BY_TYPE)
```

Please be aware that this is needed only if you are using pydantic v1. If you have already switched to the beta version of beanie with v2 support, you don't need this patch.

**Comment by siddhesh1981** [comment]
Hi @roman-right,

Thanks for the solution. Adding ENCODERS_BY_TYPE.update(PYDANTIC_ENCODERS_BY_TYPE) solved the issue.

I will like to switch to pydantic v2 and beta version of beanie, but getting bugs due to dependencies on other packages. Will try to solve them. As of now the patch you have given is working.

Regards,
Siddhesh

**Comment by Mark90** [comment]
> Hi @siddhesh1981,
> 
> To be compatible with both pydantic v1 and v2, FastAPI has its own `ENCODERS_BY_TYPE` variable that is used in the encoder. Beanie cannot patch it as it does for Pydantic. I'm checking how I can fix this for FastAPI. For now, please use the following code somewhere after importing `init_beanie`:
> 
> ```python
> from fastapi.encoders import ENCODERS_BY_TYPE
> from pydantic.json import ENCODERS_BY_TYPE as PYDANTIC_ENCODERS_BY_TYPE
> ENCODERS_BY_TYPE.update(PYDANTIC_ENCODERS_BY_TYPE)
> ```
> 
> Please be aware that this is needed only if you are using pydantic v1. If you have already switched to the beta version of beanie with v2 support, you don't need this patch.

Awesome, thanks a lot! Since fastapi 0.100.1 we were getting different errors, to be precise:

```
ValueError: [TypeError("'DBRef' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

Registering the pydantic encoders in fastapi resolved the issue. (we too are still working on updating to pydantic v2)
