### ISSUE TITLE
[BUG] Using insert_many does not trigger insert action

### ISSUE THREAD

**Issue by alex-linx** [roman-right/beanie#630]
**Describe the bug**
When using `insert_many`, actions defined using `before_event` or `after_event` are not triggered.

**To Reproduce**
This is a minimal example, in my code I have more sophisticated logic that happens, but this demonstrates the issue.

```python
class MyDocument(Document):
	insert_time: Optional[datetime] = Field(default_factory=lambda: datetime.utcnow()
	last_update_time: Optional[datetime] = Field(default_factory=lambda: datetime.utcnow()

    @before_event(Insert, Replace, Update, SaveChanges, Save)
    def update_last_update_time(self):
        self.last_update_time = datetime.utcnow()


async def main():
	my_docs = await MyDocument.find_all().to_list()
	asyncio.sleep(5)
	await MyDocument.insert_many(my_docs)
```

**Expected behavior**
I expect that the action defined for `before_event(Insert)` will be triggered on insert_many, and update the `last_update_time`.
However it doesn't happen.

If looping over the documents and running `.save()` on each one separately, it works as expected.

**Additional context**
I found that there was already an issue about this https://github.com/roman-right/beanie/issues/431 that was closed.

I think at the very least it should be documented more explicitly. For us it caused a bug that took us some time to pinpoint the exact issue.

If possible I think it would make sense that running `insert_many/replace_many` will trigger the respective actions, it feels like a natural thing to do.
Another option, like you suggested in the other issue, would be defining a separate event for `insert_many/replace_many`. In my opinion it is less intuitive to define them separately since usually (I guess) the user wants the same actions to trigger regardless of whether the document was saved separately or in bulk. But it's also a valid option.

**Comment by roman-right** [comment]
Hi! Insert many is a class method, while event-based actions work against instance methods only.

**Comment by alex-linx** [comment]
Well, maybe it's possible to define another decorator, something like this.

```
def wrap_with_actions_multiple(event_type: EventTypes):
    """
    Helper function to wrap Document class methods with
    before and after event listeners
    :param event_type: EventTypes - event types
    :return: None
    """

    def decorator(f: Callable):
        @wraps(f)
        async def wrapper(
            cls,
            *args,
            skip_actions: Optional[List[Union[ActionDirections, str]]] = None,
            **kwargs,
        ):

            if skip_actions is None:
                skip_actions = []
			
			documents = kwargs.get("documents") or args[0]
			await asyncio.gather(
			    *[
			        ActionRegistry.run_actions(
			            document,
			            event_type=event_type,
			            action_direction=ActionDirections.BEFORE,
			            exclude=skip_actions,
			        )
			        for document in documents
			    ]
			)

            result = await f(self, *args, skip_actions=skip_actions, **kwargs)

            await asyncio.gather(
			    *[
			        ActionRegistry.run_actions(
			            document,
			            event_type=event_type,
			            action_direction=ActionDirections.AFTER,
			            exclude=skip_actions,
			        )
			        for document in documents
			    ]
			)

            return result

        return wrapper

    return decorator
```

I guess it would be difficult to implement the after actions part because, the documents in the list don't get updated (if I understand correctly) - so they won't have id for instance which might cause some issues.
Maybe then say that this decorator only supports before actions, and issue a warning if there are after actions defined?
In my opinion, before_save is usually more important than after_save, since it actually affects what's written into the DB.

What do you think?
