### ISSUE TITLE
[BUG] get_settings() does not return the inherited settings

### ISSUE THREAD

**Issue by piercsi** [roman-right/beanie#644]
**Describe the bug**

When inheriting settings from a common class, get_settings() does not return the inherited settings.

**To Reproduce**

```
from beanie import Document, init_beanie
from motor.motor_asyncio import AsyncIOMotorClient
import asyncio
import datetime


class GlobalSettings(Document):
    class Settings:
        bson_encoders = {
            datetime.datetime: lambda x: x,
            datetime.date: lambda x: datetime.datetime.combine(x, datetime.time.min),
        }


class MyDates(GlobalSettings):
    d: datetime.date
    dt: datetime.datetime

    class Settings(GlobalSettings.Settings):
        name = 'mydates'


async def example():
    client = AsyncIOMotorClient("mongodb://localhost:27019/my_database")
    await init_beanie(database=client.get_database(), document_models=[MyDates])
    doc = MyDates(d=datetime.date.today(), dt=datetime.datetime.now())
    print(doc.Settings.bson_encoders)
    print(doc.get_settings().bson_encoders)


if __name__ == "__main__":
    asyncio.run(example())
```

**Expected behavior**

doc.get_settings().bson_encoders (in this case) should return the same as doc.Settings.bson_encoder, i.e. the values from the inherited class.

**Additional context**
If
```
    class Settings(GlobalSettings.Settings):
        name = 'mydates'
```
 is removed, get_settings() works as expected.

**Comment by roman-right** [comment]
Hi! Thank you for the catch. I'll check it out in the next bug-fixing session. This or next week.

**Comment by roman-right** [comment]
Hi! It looks like I cannot solve this. Overriding this behavior is possible using metaclasses. However, Pydantic already uses its metaclass there. Python doesn't allow metaclass conflicts.

If you have any ideas, please share.

**Comment by piercsi** [comment]
Thanks for taking a look. I guess all I am trying to achieve is to have some common settings to prevent duplicate code on each class as I have over 100 collections. Is there an alternative approach?

**Comment by piercsi** [comment]
Ok so something simple like this seems to work:

```
bson_encoders = {
    datetime.datetime: lambda x: x,
    datetime.date: lambda x: datetime.datetime.combine(x, datetime.time.min),
}


class MyDates(Document):
    d: datetime.date
    dt: datetime.datetime

    class Settings:
        name = 'mydates'
        bson_encoders = bson_encoders
```
