### ISSUE TITLE
[BUG] Undefined behavior when chaining update methods

### ISSUE THREAD

**Issue by alex-linx** [roman-right/beanie#646]
**Describe the bug**
There are actually 2 separate things one is a feature request, another is a bug, but I think they are connected.

The bug: When chaining update methods only the last one get's executed:
```
await MyModel.find_all().set({MyModel.field1: "a"}).set({MyModel.field2: "b"})
# Only field 2 gets updated
```

The same is also true when passing multiple arguments to update:
```
await MyModel.find_all().update({"$set": {MyModel.field1: "a"}}, "$set": {MyModel.field2: "b"})
# Only field 2 gets updated
```

I haven't played with other opearators like inc and mul but I suspect they share the same behavior.

**Expected behavior**
In case methods are chained together I expect them all to be executed.
In case multiple arguments are passed to `update()` I expect the behavior to be equivalent to chaining.

**Additional context**
I discovered this bug while trying to execute an update query with a pipeline, something like this:
```
await MyModel.find_all().set({"field1": {"$not": "$field1"}})
```
If I execute this `field1` will be set to the literal string value `'{"$not": "$field1"}'`, which is not what I want.
I want to invert the value of `field1` (it's a boolean field in this case).
I saw that you can pass pymongo a list of dictionaries in which case it will interpret it as an update pipeline, so I would like to be able to do something like this:
```
await MyModel.find_all().update([{"$set": {"field1": {"$not": "$field1"}}}])
```

But this throws an error:
```
    @property
    def update_query(self) -> Dict[str, Any]:
        query: Dict[str, Any] = {}
        for expression in self.update_expressions:
            if isinstance(expression, BaseUpdateOperator):
                query.update(expression.query)
            elif isinstance(expression, dict):
                query.update(expression)
            elif isinstance(expression, SetRevisionId):
                set_query = query.get("$set", {})
                set_query.update(expression.query.get("$set", {}))
                query["$set"] = set_query
            else:
>               raise TypeError("Wrong expression type")
E               TypeError: Wrong expression type

../../.venv/lib/python3.9/site-packages/beanie/odm/queries/update.py:83: TypeError
```

I think those issues are all related to the fact that in the `update_query` property,
the returned value is always of type dict, so pymongo will always interpret it literally and not as a pipeline.

I found a workaround for this:
```
update = MyModel.find_all().update([{"$set": {"field1": {"$not": "$field1"}}}])
update.encoders[dict] = lambda x: [x]
await update
```
But for some reason the encoders value stays there and breaks other queries as well.
So I either have to 
```
del update.encoders[dict]
```
which might not be async-safe,
or just use pymongo/motor directly.

**Comment by roman-right** [comment]
Hi! Thank you for the catch. I'll check it out in the next bug-fixing session. This or next week

**Comment by roman-right** [comment]
Hi!

You can not use the same key in python dict twice:

```python
print({"$set": {MyModel.field1: "a"}}, "$set": {MyModel.field2: "b"} )  # the second one will rewite
```

**Comment by roman-right** [comment]
Pipelines are supported in https://github.com/roman-right/beanie/pull/669. Please check. Be aware, MongoDB supports a limited list of operators in the update aggregation pipelines.
