### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pydantic_settings'

### ISSUE THREAD

**Issue by arynyklas** [roman-right/beanie#649]
**Describe the bug**
Trying to import beanie and _ModuleNotFoundError_ raises.

**To Reproduce**
```python
import beanie
```

**Expected behavior**
Successful import.

**Additional context**
I am also running pydantic v2.

Error:
`ModuleNotFoundError: No module named 'pydantic_settings'`

**Comment by roman-right** [comment]
Hi! Which version do you use? '1.21.0' doesn't use settings

**Comment by huongphamx** [comment]
Pydantic v2 split settings to dedicate module, pydantic_settings. See migration [guild](https://docs.pydantic.dev/latest/usage/pydantic_settings/) .
If you are using new FastAPI version, I think you need to install it: `pip install pydantic_settings`.
