### ISSUE TITLE
[BUG] Custom types like bson.Binary require `__get_pydantic_core_schema__`

### ISSUE THREAD

**Issue by Luc1412** [roman-right/beanie#651]
**Describe the bug**
With pydantic 2.0 custom types like in my case `bson.Binary` cause issues. You either need to create a config with `arbitrary_types_allowed = True` or implement `__get_pydantic_core_schema__`

This is the error:
```py
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'bson.binary.Binary'>. Set \`arbitrary_types_allowed=True\` in the model_config to ignore this error or implement \`__get_pydantic_core_schema__\` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.1.1/u/schema-for-unknown-type
```

**To Reproduce**
```python
class ExampleEntry(BaseModel):
    example: bson.Binary
```

**Expected behavior**
It works without any issue

**Additional context**
Discord: https://ptb.discord.com/channels/822196934973456394/822196935435747332/1138966773044101190

**Comment by roman-right** [comment]
The thing is Pydantic v2 needs some additional effort to support custom types.
I've added a type inherited from bson.Binary to Beanie. You can use it this way:

```python
from beanie import BsonBinary

class Sample(Document):
    binary_field: BsonBinary
```

Please let me know if you have any issues with it.
It is implemented in the PR: https://github.com/roman-right/beanie/pull/669

**Comment by Luc1412** [comment]
There is an issue with the `subtype`. When using `BsonBinary` the `subtype` seems to be always 0. Before it was properly set, in my case 6.

**Comment by Luc1412** [comment]
@roman-right Any news regarding this?

**Comment by gsakkis** [comment]
Should have been fixed by https://github.com/roman-right/beanie/pull/739

**Comment by Luc1412** [comment]
Thanks, your PR solved this issue.
