### ISSUE TITLE
[BUG] Error when a nested field name equals a `string` method

### ISSUE THREAD

**Issue by akriese** [roman-right/beanie#674]
**Describe the bug**
When accessing a nested field in a beanie operator, an error is thrown when that nested field's name is equal to one of the python builtin `string` methods, like `center`, `index`, `strip`, `split` etc.
The error occurs, when beanie tries to split the path into its segements.
```
  File "C:\...\beanie\odm\utils\relations.py", line 21, in convert_ids
    k_splitted = k.split(".")
                 ^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'split'
```
Example for better understanding:
```python

class Geo(BaseModel):
    type: str
    coordinates: list[float]

class Location(BaseModel):
    center: Geo
    info: str

class Point(Document):
    location: Location

await Point.find(Near(Point.location.center, 30, 34))
```
Apparently, the parent of the nested field (e.g. Point.location) is at that point in the code a string. And the dot-operator with a `string` method (e.g. center) makes python think, that the object `Point.location.center` is a method instead of a string.

**To Reproduce**
See snippet above.

**Expected behavior**
The nested field name does not matter and is not treated as a `string` method.

**Additional context**
This problem only occurs with nested field names, not in the first level inside the tree. (At least, as far as I tried...)
I think, it might be connected to two other issues I found here, that were complaining about nested field aliases not being used correctly (#124 , #369), which were both auto-closed after some time. I might be wrong tho. 

In the meantime, I'll have to rename my fields or write `"points.location.center"` instead, which is not very nice regarding stuff like LSP and completion.
Happy to hear from you about this :)

**Comment by roman-right** [comment]
Hi @akriese ,
Thank you for the report. It is very interesting problem.
The thing is - I do some magic to support things like `Point.location.center` in query builder. For classes I replace all the fields with instances of `ExpressionField(str)`. For classes only - so on the instance level it stay the same. I need it to be inherited from string as I provide the as a key of the mongodb query later. And here is the magic limitation - str has own methods (like `center`). I don't know yet how to fix it without global rework. If you have any ideas - please let me know.
