### ISSUE TITLE
[BUG] Projection not working

### ISSUE THREAD

**Issue by msenol86** [roman-right/beanie#688]
.find(..., projection={"a_field": True}) is not working. I get error:
`pymongo.collection.Collection.find_one() got multiple values for keyword argument 'projection'
`
```python
await MetricTypeDocument.find_one({"name": "bad_rate"})
MetricTypeDocument(id=ObjectId('64e894acd6d429e6f6aa6566'), revision_id=None, name='bad_rate', definition={}, legacy_keys=['TMP Test Bad Rate', 'KFO Test Bad Rate', 'SFO Test Bad Rate', 'SFO Test Bad Rate (Thr.: 0.80)', 'KFO Test Bad Rate (Thr.: 0.80)', 'TMP Test Bad Rate (Thr.: 0.80)'], updated_by=<beanie.odm.fields.Link object at 0x7f4631163400>, created_by=None, updated_at=datetime.datetime(2023, 5, 10, 8, 31, 32, 653000), created_at=datetime.datetime(2023, 4, 20, 12, 7, 12, 274000))
await MetricTypeDocument.find_one({"name": "bad_rate"}, projection={"name": True})
TypeError: pymongo.collection.Collection.find_one() got multiple values for keyword argument 'projection'

```

**Comment by roman-right** [comment]
Hey @msenol86 ,
You should use `projection_model` parameter instead.
Here is the example:
```python
import asyncio

import motor
from pydantic import BaseModel

from beanie import Document, init_beanie


class MetricTypeDocument(Document):
    name: str
    definition: dict
    legacy_keys: list

    class Settings:
        name = "metric_type"


class MetricTypeProjection(BaseModel):
    name: str


async def main():
    client = motor.motor_asyncio.AsyncIOMotorClient("mongodb://beanie:beanie@localhost:27017")
    db = client.beanie_db
    await init_beanie(
        db,
        document_models=[MetricTypeDocument],
    )

    await MetricTypeDocument(name="bad_rate", definition={
        "name": "bad_rate",
    }, legacy_keys=[
        "bad_rate",
    ]).save()

    result = await MetricTypeDocument.find_one({"name": "bad_rate"}, projection_model=MetricTypeProjection)
    print(result)


asyncio.run(main())

```

Did you find this in the doc? If yes, please provide the link - I'll change.

**Comment by hgalytoby** [comment]
> @roman-right I'm going to add this here as it somewhat fits the issue. I was just looking for a way to use very simple "on-the-fly" projection models like this:
> 
> ```
> await SomeDocument.find_one({"foo": "bar"}, projection={"foo": True})
> ```
> 
> or
> 
> ```
> await SomeDocument.find_one({"foo": "bar"}).project({"foo": True})
> ```
> 
> Because quite often one needs a very special but simple projection exclusively for this one DB request. Preparing an extra model for this somewhere else seems to unnecessarily fracture the code. Do you think this could be a viable feature?

I also hope that there will be such a function.
