### ISSUE TITLE
 [improvement] Find-queries result type annotation

### ISSUE THREAD

**Issue by roman-right** [roman-right/beanie#69]
The current result annotation is BaseModel, which is not reflecting the real use-cases. It should be Generic for the projection model or for the original document class.

**Comment by KiraPC** [comment]
@roman-right I was trying to figure out how can I achieve this goal, but I cannot.

Do you have some ideas?

I would like to have this feature.

**Comment by roman-right** [comment]
@KiraPC 
 As I see this, it is definitely some trick with generic types. I didn't find a solution to this puzzle yet, unfortunately. 
 But I'm on it and don't lose hope :)

**Comment by KiraPC** [comment]
@roman-right Yeah, I was playing with generic before writing this comment and couldn't find a way.

I'll try to do the same. If I'll figure out I'll open a PR

**Comment by KiraPC** [comment]
Opened PR: https://github.com/roman-right/beanie/pull/81

**Comment by roman-right** [comment]
Done
