### ISSUE TITLE
[BUG] alias are ignored in model_dump for the documents in Link

### ISSUE THREAD

**Issue by RobertoBochet** [roman-right/beanie#705]
**Describe the bug**
Hi, another bug related to migration to pydantic v2. In the case you have a `Document` with a field of type `Link` to another `Document`, when you try to perform a `model_dump` of the root `Document` requiring the use of the **alias** this directive is applied only for the root `Document` 

**To Reproduce**
```python
class C(Document):
    a: Annotated[str, Field(alis="_a")] = 'f'

class D(Document):
    c: Link[C]

c = C()
await c.save()
c = await C.get(c.id)
d = D(c=c)
await d.save()
d = await D.get(d.id)
await d.fetch_all_links()
d.model_dump(by_alias=True)
```
This results in 
```json
{'_id': '6503b090ba1e38cf02b18fc1', 'c': {'id': '6503b090ba1e38cf02b18fc0', 'a': 'f'}}
```

**Expected behavior**
The example above should return
```json
{'_id': '6503b090ba1e38cf02b18fc1', 'c': {'_id': '6503b090ba1e38cf02b18fc0', '_a': 'f'}}
```

**Additional context**
```
python=="3.11.5"
pydantic=="2.3.0"
beanie=="1.22.1"
```
In FastAPI this bug prevents the use of `Link` in the response models

Thank so much for your work

**Comment by roman-right** [comment]
Hi! Thank you for the catch. I'll check and fix it this/next week.
