### ISSUE TITLE
Linked Documents Nested Inside Embedded Models Aren't Saved to Their Own Collections

### ISSUE THREAD

**Issue by mhdzumair** [roman-right/beanie#724]
**Describe the bug**
When using the `Link `field inside nested `BaseModels` and trying to insert the parent `Document`, Beanie does not save the linked document in its own separate collection as expected. Instead, it treats the linked document as an embedded document inside the parent `Document`, saving it directly within the parent document's collection.

**To Reproduce**
```python
import asyncio
import motor.motor_asyncio
from beanie import init_beanie, Document, Link, WriteRules
from pydantic import BaseModel

DATABASE_URL = "mongodb://localhost:27017"
DATABASE_NAME = "test_beanie_db"
client = motor.motor_asyncio.AsyncIOMotorClient(DATABASE_URL)
database = client[DATABASE_NAME]

class Streams(Document):
    torrent_name: str
    filename: str
    class Settings:
        collection = "streams"

class Episode(BaseModel):
    episode_number: int
    streams: list[Link[Streams]]

class Season(BaseModel):
    season_number: int
    episodes: list[Episode]

class Series(Document):
    title: str
    seasons: list[Season]
    class Settings:
        collection = "series"

async def run():
    await init_beanie(
        database=database,
        document_models=[Streams, Series],
    )
    # Inserting a series
    stream = Streams(torrent_name="sample_torrent", filename="sample_file.mkv")
    episode = Episode(episode_number=1, streams=[stream])
    season = Season(season_number=1, episodes=[episode])
    series = Series(title="Sample Series", seasons=[season])
    await series.insert(link_rule=WriteRules.WRITE)
    # Check collections
    streams_in_db = await Streams.find_all().to_list()
    series_in_db = await Series.get(series.id)
    print(streams_in_db)
    print(series_in_db)

asyncio.run(run())

```

**Expected behavior**
The `Streams` document should be stored in its own `streams` collection. The `Series` document should only have a reference/link to the `Streams` document.

**Current behavior**
The `Streams` data is embedded within the Series collection instead of being referenced from its own `streams` collection.

**Additional context**
This issue arises particularly when using nested `BaseModel` structures and trying to store linked documents from within these nested structures.

**Comment by roman-right** [comment]
Hi! Thank you for the catch. I'll check and fix it this/next week.

**Comment by mhdzumair** [comment]
You can close this story.
