### ISSUE TITLE
[discussion] Add pytest to pre-commit

### ISSUE THREAD

**Issue by jorants** [roman-right/beanie#73]
Should we add pytest to pre-commit? It would slow down commits but you would probably want to run it anyway.

**Comment by roman-right** [comment]
I think this is not necessary. Sometimes commits are not related to code changes. In that cases, it would be uncomfortable to wait some minutes to be approved to push a typo fix, for example. As tests are running on the pull request step anyway, I'd say we can to not add them to the pre-commit config.
