### ISSUE TITLE
[BUG] issue with caching and statemanagement

### ISSUE THREAD

**Issue by CAPITAINMARVEL** [roman-right/beanie#732]
**Describe the bug**

**To Reproduce**
```python
class Sample(Document):
    num: int
    name: str

    class Settings:
        use_state_management = True
        use_cache = True

        doc_test = Sample(num=500, name= "Test")
        await doc_test.create()
        s = await Sample.find_one(Sample.name == "Test")
        assert s
        s.num = 1000
        await s.save_changes()
        print(await Sample.find_one(Sample.name == "Test"))
```

**Expected behavior**
on the new document i should get it with 1000 instead of 500 but it doesnt keep track and it stay the same from cache

**Comment by roman-right** [comment]
Hi @CAPITAINMARVEL,
This is the expected behavior. I plan to add a method to invalidate the cache. However, implementing the updating of cached results based on the database's update operations is not on the to-do list.

**Comment by xtay** [comment]
> Hi @CAPITAINMARVEL, This is the expected behavior. I plan to add a method to invalidate the cache. However, implementing the updating of cached results based on the database's update operations is not on the to-do list.

Agree with CAPITAINMARVEL.

I don't think this behavior is ok for a "cache",
a "cache" should no be a distraction. it should do its work and give results as if it were not there（just be faster or reduce io）.

**Comment by mbUSC** [comment]
@roman-right I was also stumped by this behavior unfortunately. 
Like @CAPITAINMARVEL and @xtay, I find it confusing and it makes this feature not very useful in a lot of scenarios.

An actual transparent cache would be awesome

**Comment by dpkpx** [comment]
I also faced same issue and created a workaround by inspecting the beanie odm/cache.py and writing a class method  in you document model something like this...

```
class Sample(Document):
    num: int
    description: str

    @classmethod
    def clear_ cache(cls):
        cls._cache.cache = collections.OrderedDict()
```

It will clear all cache for that model

**Comment by martinbndr** [comment]
Just start working with beanie, also came across this issue.
Created a model with caching enabled and tried updating some values. While re-requesting the model again it still show the old value before it was updated. 
Ig this behaviour is still unsolved.
I would expect the cache to be updated to make acual profit of the caching feature.

Any plan on implementing this?

**Comment by staticxterm** [comment]
Hi @martinbndr,
Beanie development is kind of "dead" lately.
PRs are welcome.

I myself also don't see a use case for why would anyone use this type of cache if changes to the database or to the cached objects are inevitable.
