### ISSUE TITLE
[improvement] Chaining keeps original query

### ISSUE THREAD

**Issue by jorants** [roman-right/beanie#74]
Consider the following test:
```python
async def test_find_changed(preset_documents):
    query1 = Sample.find_many(Sample.integer > 1)
    query2 = query1.find_many(Sample.nested.optional == None)
    assert await query1.to_list() != await query2.to_list()
```
This fails as the `query2 = ...` line also changes the first query. Should this instead return a new object with the parameters set differently?

**Comment by roman-right** [comment]
The thing is, `query1` is a FindQuery object, which supports chaining operations. Like 
```python
Sample.find(...).find(...).find(...).sort(..))
```
But your point is very good. As FindQuery is in fact a mutable object, I think for this case it would be good to implement `__copy__` (and even `__deepcopy__`) method to follow the pythonic way here. To be able to do things like:
```python
async def test_find_changed(preset_documents):
    query1 = Sample.find_many(Sample.integer > 1)
    query2 = copy(query1).find_many(Sample.nested.optional == None)
    assert await query1.to_list() != await query2.to_list()
```

What do you think about this?

**Comment by jorants** [comment]
I'm also working on rewriting the Query classes to merge the `Many` and `One` versions as i mentioned on the discord. For that I was trying to change this as well by copying by default when the chaining functions are called. I think something can be sad for both ways. Maybe wait a bit till I get my rewrites working as it would be trivial to change those to your suggestion and then see what works better?

**Comment by roman-right** [comment]
Yes. I saw the commit, you accidentally pushed to another PR. Some things are really good like `__await__` def with `to_list` inside for the group search. And I had some questions also. Looking forward to the final version of this. If you would like to discuss it - I'm open for talks :-)

Also, sorry for the off-topic, could you pls take a look at your discord? I texted you there with my new project idea. Probably it would be interesting for you to join.
