### ISSUE TITLE
[BUG] Optional[BackLinks] return beanie.odm.fields.BackLink object

### ISSUE THREAD

**Issue by Nicialy** [roman-right/beanie#749]
**Describe the bug**
BackLink with None Create return dont None

**To Reproduce**
```python

class Sprint(Document, SprintCreation):
    id: UUID = Field(default_factory=uuid4)
    issues: List[Link["Issue"]] = Field(default_factory=list)

class Issue(Document, IssueBase):
    id: UUID = Field(default_factory=uuid4)
    creation_date: datetime = Field(default_factory=datetime.now)
    sprint: Optional[BackLink["Sprint"]] = Field(default=None,original_field="issues", exclude=True)

issue = Issue(**issue_creation.model_dump(),sprint=None)
issue = await Issue.find_one(Issue.id == issue_id, fetch_links=True)
if issue.sprint == None or issue_creation.sprint_id != issue.sprint.id:
            issue.sprint.issues.remove(issue.id)

```

**Expected behavior**
 I want issue.sprint == None true

![image](https://github.com/roman-right/beanie/assets/43730314/885ef021-9a1d-4fe9-bb0e-93bee9917571)
![image](https://github.com/roman-right/beanie/assets/43730314/08511ea9-be84-4712-88ba-4d52709eac1e)

**Comment by roman-right** [comment]
Hi! Could you please provide on-module example of this behavior which I can run locally to check, what is happening?

**Comment by Nasochec** [comment]
Example:
[main.py.txt](https://github.com/roman-right/beanie/files/13266539/main.py.txt)

**Comment by Nicialy** [comment]
```python
from motor.motor_asyncio import AsyncIOMotorClient

from typing import Optional
from pydantic import Field
import asyncio
from beanie import init_beanie,Document,BackLink,Link
from beanie.odm.fields import PydanticObjectId

class Country(Document):
    id: PydanticObjectId = Field(default_factory=PydanticObjectId)
    cities: list[Link["City"]] = Field(default_factory=list)

class City(Document):
    id: PydanticObjectId = Field(default_factory=PydanticObjectId)
    country: Optional[BackLink["Country"]] = Field(default=None, original_field="cities", exclude=True)

__beanie_models__=[Country,City]

async def fillSomeData(): 
    session:AsyncIOMotorClient  = AsyncIOMotorClient("mongodb://localhost:27017")
    await init_beanie(database=session.example, document_models=__beanie_models__)
  
    cityOk = City()
    await cityOk.create()
    # cityOk.country = <beanie.odm.fields.BackLink object at > expected None
    
    country = Country()
    country.cities.append(cityOk)
    await country.save()

    cityErr = City()
    await cityErr.create()
    # cityErr.country = <beanie.odm.fields.BackLink object at > expected None

    id = cityOk.id
    id1 = cityErr.id
    city = await City.find_one(City.id==id, fetch_links=True)
    city1 = await City.find_one(City.id==id1, fetch_links=True)

    print(city.country)#  country = Country(id=ObjectId('6548dd0f4 ... 
    print(city1.country)# country = <beanie.odm.fields.BackLink object at > expected None

if __name__ == "__main__":
    asyncio.run(fillSomeData())

```

**Comment by Nicialy** [comment]
they forgot about us...

**Comment by roman-right** [comment]
Hi @Nicialy and @Nasochec ,
First of all, there are not so many "they" here :D. Sorry for the delay.

I investigated this problem. It is a bit of trade off. BackLink is a virtual field. It means Beanie never stores this field to the database, it only populates it on finds with `fetch_links=True`. It means that if `fetch_links != True` Beanie has no information about if such relations exist or not. But Links (and BackLinks) can be fetched directly using `fetch` method. But to be able to run this method this field should be an object of BackLink. And, as Beanie on the filed level doesn't know if there is no such relation or relation was not fetched, it always creates an empty BackLink object for such fields.

I understand, that it is confusing. But I didn't find a good solution to handle it equally for all the cases. Like I can understand, that nothing was returned back using `fetch_links==True` and put None there, but I can not understand, what should be set there, if `fetch_links==False`. And I can not handle these two scenarios differently, as it will not be consistent.

I'm open for suggestions. If you have any ideas about this case, please share. We can discuss it in real-time on the Discord server. Or here, for sure.

Thank you for the catch. This topic definitely needs more investigation.
