### ISSUE TITLE
[BUG] Document.json doesn't work with pydantic 2.0

### ISSUE THREAD

**Issue by Luc1412** [roman-right/beanie#767]
**Describe the bug**
TypeError: `dumps_kwargs` keyword arguments are no longer supported.

**To Reproduce**
```python
MyDocument().json()
```

**Expected behavior**
I get a json of my object

**Additional context**

**Comment by IterableTrucks** [comment]
It's a breaking change from pydantic v2. `BaseModel.json` has been changed to `BaseModel.model_dump_json`
