### ISSUE TITLE
How do you do relations between documents in beanie?

### ISSUE THREAD

**Issue by nickleman** [roman-right/beanie#8]
Is there a way to automate relationships between documents in beanie or do you have to do it manually? If manually, are we able to access the ObjectId parameter of the document or should we just ensure that we have an index on a unique field? Also, can we set the unique field of an index to assist with this? I didn't see anything in the documentation about support of the unique flag of indexes. This may actually be multiple issues and let me know and I can split it up if you'd prefer.

**Comment by roman-right** [comment]
Hello,

Yes, it is assumed to do it manually.
Every document contains `id` field - it is `ObjectId` (`PydanticObjectId` to be fair). You can use it to set the relations. 
It is not documented. Nice catch - I'll clarify this.
Also, you can create a unique index. I'll show in example:

```python
class DocumentTestModelWithIndex(Document):
    test_int: int
    test_list: List[SubDocument]
    test_str: str

    class Collection:
        indexes = [
            IndexModel(
                [("test_str", pymongo.ASCENDING)],
                unique=True,
            ),
        ]
```
It can be used then to map the objects too.
All the `IndexModel` parameters can be found here - https://pymongo.readthedocs.io/en/stable/api/pymongo/operations.html#pymongo.operations.IndexModel

I'll add an example of `unique` usage to the doc too. Thank you :-)

**Comment by nickleman** [comment]
Sounds good, thank you.

**Comment by roman-right** [comment]
Welcome!
If you will need any help, ask here or in discord.
