### ISSUE TITLE
[examples] Update example projects

### ISSUE THREAD

**Issue by roman-right** [roman-right/beanie#90]
There two official example projects:

- [FastAPI Demo](https://github.com/roman-right/beanie-fastapi-demo) - Beanie and FastAPI collaboration demonstration. CRUD and Aggregation.
- [Indexes Demo](https://github.com/roman-right/beanie-index-demo) - Regular and Geo Indexes usage example wrapped to a microservice.

Both should:
- Show, how to use current Beanie syntax
- Contain unit tests

**Comment by rohiti** [comment]
Hi @roman-right ,

I am trying to use Beanie with Geospatial queries. But unable to do so based on the current documentation, would you be able to provide some help?

I need to simply run a find query based on the coordinates and store the calculated distance in another field defined in my projection model.
