### ISSUE TITLE
Beanie aggregation

### ISSUE THREAD

**Issue by BobbyLeeSH** [roman-right/beanie#92]
Hey Roman,

I tried to use max() aggregation but it seems like it gets an error when there is no documents found, because it tries to access 0th element in the documents found.

Is this intended? Or is it supposed to give default value like 0?

Cheers.

**Comment by roman-right** [comment]
Hi @BobbyLeeSH ,
This is definitely a bug. I'll fix it asap. Thank you!

**Comment by roman-right** [comment]
Hi @BobbyLeeSH ,
It looks like I fixed this. Version `1.2.4`

Feel free to reopen this if you will face any wrong behavior.
